import { z } from "zod";
import { inventoryDocumentPatchSchema, inventoryDocumentSchema, postDocumentSchema, reverseDocumentSchema, warehouseListQuerySchema } from "@/features/warehouse/schemas/warehouseSchemas";
import { createDocument, getDocument, listDocuments, postDocument, reverseDocument, updateDocument } from "@/features/warehouse/services/warehouseRepository";
import type { InventoryDocumentType } from "@/features/warehouse/types/warehouseTypes";
import { AppError, errorResponse } from "@/lib/api/errors"; import { successResponse } from "@/lib/api/responses"; import { parseJsonBody,parseWithSchema } from "@/lib/api/validation"; import { getRequestUser } from "@/services/auth/getRequestUser"; import { requireAuthenticatedUser } from "@/services/authorization/requirePermission";
const idSchema=z.object({id:z.string().uuid()});
export async function documentList(request:Request,type:Exclude<InventoryDocumentType,"reversal">){try{return successResponse(await listDocuments(requireAuthenticatedUser(await getRequestUser()),type,parseWithSchema(warehouseListQuerySchema,Object.fromEntries(new URL(request.url).searchParams))));}catch(error){return errorResponse(error);}}
export async function documentCreate(request:Request,type:Exclude<InventoryDocumentType,"reversal">){try{let body:unknown;try{body=await request.json();}catch{throw new AppError("VALIDATION_ERROR","Nội dung yêu cầu không hợp lệ.");}const input=parseWithSchema(inventoryDocumentSchema,{...(body as object),type});return successResponse(await createDocument(requireAuthenticatedUser(await getRequestUser()),input),{status:201});}catch(error){return errorResponse(error);}}
export async function documentDetail(params:Promise<{id:string}>,type:Exclude<InventoryDocumentType,"reversal">){try{const{id}=parseWithSchema(idSchema,await params),document=await getDocument(requireAuthenticatedUser(await getRequestUser()),id);if(document.type!==type)throw new AppError("NOT_FOUND","Không tìm thấy chứng từ.");return successResponse(document);}catch(error){return errorResponse(error);}}
export async function documentUpdate(request:Request,params:Promise<{id:string}>,type:Exclude<InventoryDocumentType,"reversal">){try{const{id}=parseWithSchema(idSchema,await params),current=await getDocument(requireAuthenticatedUser(await getRequestUser()),id);if(current.type!==type)throw new AppError("NOT_FOUND","Không tìm thấy chứng từ.");return successResponse(await updateDocument(requireAuthenticatedUser(await getRequestUser()),id,await parseJsonBody(request,inventoryDocumentPatchSchema)));}catch(error){return errorResponse(error);}}
export async function documentPost(request:Request,params:Promise<{id:string}>,type:Exclude<InventoryDocumentType,"reversal">){try{const{id}=parseWithSchema(idSchema,await params),current=await getDocument(requireAuthenticatedUser(await getRequestUser()),id);if(current.type!==type)throw new AppError("NOT_FOUND","Không tìm thấy chứng từ.");return successResponse(await postDocument(requireAuthenticatedUser(await getRequestUser()),id,await parseJsonBody(request,postDocumentSchema)));}catch(error){return errorResponse(error);}}
export async function documentReverse(request:Request,params:Promise<{id:string}>,type:"receipt"|"issue"){try{const{id}=parseWithSchema(idSchema,await params),current=await getDocument(requireAuthenticatedUser(await getRequestUser()),id);if(current.type!==type)throw new AppError("NOT_FOUND","Không tìm thấy chứng từ.");return successResponse(await reverseDocument(requireAuthenticatedUser(await getRequestUser()),id,await parseJsonBody(request,reverseDocumentSchema)));}catch(error){return errorResponse(error);}}
