"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/shared/Button";
import { Card } from "@/components/shared/Card";
import type { LeavePolicy, LeaveType } from "@/features/leave/types/leaveTypes";

type Workflow={id:string;code:string;name:string;active:boolean;steps:{id:string;stepOrder:number;approverSource:string;specificAccountId?:string;specificRoleCode?:string}[]};
const sourceLabels:Record<string,string>={direct_manager:"Quản lý trực tiếp",department_manager:"Trưởng phòng",specific_role:"Vai trò chỉ định",specific_user:"Người dùng chỉ định",hr_role:"Nhân sự"};

export function LeaveSettings({section}:{section:"types"|"workflows"|"policies"}){
  const [types,setTypes]=useState<LeaveType[]>([]);const [workflows,setWorkflows]=useState<Workflow[]>([]);const [policy,setPolicy]=useState<LeavePolicy>();const [error,setError]=useState("");
  const [typeForm,setTypeForm]=useState({code:"",name:"",tone:"info",deductsBalance:true,requiresReason:true,requiresAttachment:false,allowsHalfDay:true,allowsMultiDay:true,workflowId:"",active:true});
  const [workflowForm,setWorkflowForm]=useState({code:"",name:"",approverSource:"direct_manager",specificRoleCode:""});
  const [workflowSteps,setWorkflowSteps]=useState<Array<{approverSource:string;specificRoleCode?:string}>>([]);
  const reload=()=>Promise.all([fetch("/api/v1/leave-types").then(r=>r.json()),fetch("/api/v1/leave-workflows").then(r=>r.json()),fetch("/api/v1/leave-policies").then(r=>r.json())]).then(([a,b,c])=>{setTypes(a.data??[]);setWorkflows(b.data??[]);setPolicy(c.data);setTypeForm(value=>({...value,workflowId:value.workflowId||(b.data?.[0]?.id??"")}));});
  useEffect(()=>{void reload().catch(value=>setError(value.message));},[]);
  async function post(url:string,payload:object){setError("");const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok){setError(body.error?.message);return false;}await reload();return true;}
  async function createType(){if(await post("/api/v1/leave-types",typeForm))setTypeForm(value=>({...value,code:"",name:""}));}
  function addWorkflowStep(){const step={approverSource:workflowForm.approverSource,...(workflowForm.approverSource==="specific_role"?{specificRoleCode:workflowForm.specificRoleCode}:{})};setWorkflowSteps(current=>[...current,step]);}
  async function createWorkflow(){const currentStep={approverSource:workflowForm.approverSource,...(workflowForm.approverSource==="specific_role"?{specificRoleCode:workflowForm.specificRoleCode}:{})};const steps=workflowSteps.length?workflowSteps:[currentStep];if(await post("/api/v1/leave-workflows",{code:workflowForm.code,name:workflowForm.name,steps})){setWorkflowForm({code:"",name:"",approverSource:"direct_manager",specificRoleCode:""});setWorkflowSteps([]);}}
  async function savePolicy(){if(!policy)return;setError("");const response=await fetch("/api/v1/leave-policies",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(policy)});const body=await response.json();if(!response.ok)setError(body.error?.message);else setPolicy(body.data);}
  const typeUpdate=(key:string,value:string|boolean)=>setTypeForm(current=>({...current,[key]:value}));
  if(section==="types")return <div className="leave-settings-grid"><Card><h3>Loại nghỉ</h3><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Mã</th><th>Tên</th><th>Trừ phép</th><th>Tài liệu</th><th>Trạng thái</th></tr></thead><tbody>{types.map(item=><tr key={item.id}><td>{item.code}</td><td>{item.name}</td><td>{item.deductsBalance?"Có":"Không"}</td><td>{item.requiresAttachment?"Bắt buộc":"Không"}</td><td>{item.active?"Hoạt động":"Tắt"}</td></tr>)}</tbody></table></div></Card><Card><h3>Thêm loại nghỉ</h3><div className="leave-form"><label><span>Mã</span><input value={typeForm.code} onChange={e=>typeUpdate("code",e.target.value.toUpperCase())}/></label><label><span>Tên</span><input value={typeForm.name} onChange={e=>typeUpdate("name",e.target.value)}/></label><label><span>Quy trình</span><select value={typeForm.workflowId} onChange={e=>typeUpdate("workflowId",e.target.value)}>{workflows.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{[["deductsBalance","Trừ phép năm"],["requiresReason","Yêu cầu lý do"],["requiresAttachment","Yêu cầu tài liệu"],["allowsHalfDay","Cho phép nửa ngày"],["allowsMultiDay","Cho phép nhiều ngày"],["active","Hoạt động"]].map(([key,label])=><label className="checkbox-row" key={key}><input type="checkbox" checked={Boolean(typeForm[key as keyof typeof typeForm])} onChange={e=>typeUpdate(key,e.target.checked)}/><span>{label}</span></label>)}<Button variant="primary" onClick={()=>void createType()}>Thêm</Button>{error?<p className="form-error">{error}</p>:null}</div></Card></div>;
  if(section==="workflows")return <div className="leave-settings-grid"><div className="page-stack">{workflows.map(item=><Card key={item.id}><div className="leave-detail-heading"><h3>{item.name}</h3><span>{item.active?"Hoạt động":"Tắt"}</span></div><ol className="approval-timeline">{item.steps.map(step=><li key={step.id}>Bước {step.stepOrder}: {sourceLabels[step.approverSource]??step.approverSource}</li>)}</ol></Card>)}</div><Card><h3>Thêm quy trình</h3><div className="leave-form"><label><span>Mã</span><input value={workflowForm.code} onChange={e=>setWorkflowForm({...workflowForm,code:e.target.value.toUpperCase()})}/></label><label><span>Tên</span><input value={workflowForm.name} onChange={e=>setWorkflowForm({...workflowForm,name:e.target.value})}/></label><label><span>Người duyệt</span><select value={workflowForm.approverSource} onChange={e=>setWorkflowForm({...workflowForm,approverSource:e.target.value})}>{Object.entries(sourceLabels).filter(([key])=>key!=="specific_user").map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{workflowForm.approverSource==="specific_role"?<label><span>Mã vai trò</span><input value={workflowForm.specificRoleCode} onChange={e=>setWorkflowForm({...workflowForm,specificRoleCode:e.target.value})}/></label>:null}{workflowSteps.length?<ol className="approval-timeline">{workflowSteps.map((step,index)=><li key={`${step.approverSource}-${index}`}>Bước {index+1}: {sourceLabels[step.approverSource]??step.approverSource} <button type="button" onClick={()=>setWorkflowSteps(current=>current.filter((_,position)=>position!==index))}>Xóa</button></li>)}</ol>:null}<div className="form-actions"><Button onClick={addWorkflowStep}>Thêm bước</Button><Button variant="primary" onClick={()=>void createWorkflow()}>Tạo quy trình</Button></div>{error?<p className="form-error">{error}</p>:null}</div></Card></div>;
  return <Card>{policy?<div className="leave-form"><label><span>Ngày nghỉ cuối tuần (0=CN, 6=T7)</span><input value={policy.weekendDays.join(", ")} onChange={event=>setPolicy({...policy,weekendDays:event.target.value.split(",").map(Number).filter(value=>value>=0&&value<=6)})}/></label><label className="checkbox-row"><input type="checkbox" checked={policy.allowNegativeBalance} onChange={event=>setPolicy({...policy,allowNegativeBalance:event.target.checked})}/><span>Cho phép âm phép</span></label><label className="checkbox-row"><input type="checkbox" checked={policy.allowWithdrawPending} onChange={event=>setPolicy({...policy,allowWithdrawPending:event.target.checked})}/><span>Cho phép thu hồi khi chờ duyệt</span></label><label className="checkbox-row"><input type="checkbox" checked={policy.cancellationRequiresApproval} onChange={event=>setPolicy({...policy,cancellationRequiresApproval:event.target.checked})}/><span>Hủy đơn cần HR phê duyệt</span></label><label className="checkbox-row"><input type="checkbox" checked={policy.carryoverEnabled} onChange={event=>setPolicy({...policy,carryoverEnabled:event.target.checked})}/><span>Chuyển phép sang năm sau</span></label><label><span>Số ngày chuyển tối đa</span><input type="number" min="0" value={policy.carryoverMaxDays} onChange={event=>setPolicy({...policy,carryoverMaxDays:Number(event.target.value)})}/></label><Button variant="primary" onClick={()=>void savePolicy()}>Lưu</Button>{error?<p className="form-error">{error}</p>:null}</div>:"Đang tải…"}</Card>;
}
