"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/shared/Button";
import { Card } from "@/components/shared/Card";
import type { LeaveBalance, LeaveType } from "@/features/leave/types/leaveTypes";

const today=new Date().toISOString().slice(0,10);
export function LeaveRequestForm(){
  const router=useRouter();const [types,setTypes]=useState<LeaveType[]>([]);const [balances,setBalances]=useState<LeaveBalance[]>([]);const [serverDays,setServerDays]=useState<number>();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [file,setFile]=useState<File|null>(null);
  const [form,setForm]=useState({leaveTypeId:"",startDate:today,endDate:today,startDayPart:"full_day",endDayPart:"full_day",reason:""});
  useEffect(()=>{Promise.all([fetch("/api/v1/leave-types").then(r=>r.json()),fetch(`/api/v1/leave-balances?year=${new Date().getFullYear()}`).then(r=>r.json())]).then(([typeBody,balanceBody])=>{const active=(typeBody.data??[]).filter((item:LeaveType)=>item.active);setTypes(active);setBalances(balanceBody.data?.balances??[]);if(active[0])setForm(value=>({...value,leaveTypeId:active[0].id}));}).catch(value=>setError(value.message));},[]);
  useEffect(()=>{if(!form.leaveTypeId)return;const timer=setTimeout(()=>{void fetch("/api/v1/leave-requests/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,reason:form.reason||"Dự kiến"})}).then(r=>r.json()).then(body=>{if(body.ok){setServerDays(body.data.days);if(body.data.balance)setBalances(current=>[...current.filter(item=>item.leaveTypeId!==body.data.balance.leaveTypeId),body.data.balance]);}});},250);return()=>clearTimeout(timer);},[form]);
  const selectedType=types.find(type=>type.id===form.leaveTypeId);const selectedBalance=balances.find(balance=>balance.leaveTypeId===form.leaveTypeId);
  const localEstimate=useMemo(()=>{const start=new Date(`${form.startDate}T00:00:00`);const end=new Date(`${form.endDate}T00:00:00`);if(Number.isNaN(+start)||Number.isNaN(+end)||end<start)return 0;let days=0;for(let value=new Date(start);value<=end;value.setDate(value.getDate()+1))if(value.getDay()!==0&&value.getDay()!==6)days++;if(days&&form.startDayPart!=="full_day")days-=.5;if(days&&form.endDayPart!=="full_day"&&form.endDate!==form.startDate)days-=.5;return days;},[form]);const estimate=serverDays??localEstimate;
  const update=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  async function save(submit:boolean){setBusy(true);setError("");try{let response=await fetch("/api/v1/leave-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});let body=await response.json();if(!response.ok)throw new Error(body.error?.message);let item=body.data;if(file){const data=new FormData();data.set("file",file);response=await fetch(`/api/v1/leave-requests/${item.id}/attachments`,{method:"POST",body:data});body=await response.json();if(!response.ok)throw new Error(body.error?.message);response=await fetch(`/api/v1/leave-requests/${item.id}`);body=await response.json();item=body.data;}if(submit){response=await fetch(`/api/v1/leave-requests/${item.id}/submit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:item.version})});body=await response.json();if(!response.ok)throw new Error(body.error?.message);}router.push(`/leave/requests/${item.id}`);router.refresh();}catch(value){setError(value instanceof Error?value.message:"Không thể lưu đơn.");}finally{setBusy(false);}}
  return <Card><form className="leave-form" onSubmit={event=>{event.preventDefault();void save(true);}}><div className="form-grid"><label><span>Loại nghỉ</span><select required value={form.leaveTypeId} onChange={event=>update("leaveTypeId",event.target.value)}>{types.map(type=><option key={type.id} value={type.id}>{type.name}</option>)}</select></label><label><span>Từ ngày</span><input type="date" required value={form.startDate} onChange={event=>update("startDate",event.target.value)}/></label><label><span>Buổi bắt đầu</span><select value={form.startDayPart} onChange={event=>update("startDayPart",event.target.value)}><option value="full_day">Cả ngày</option><option value="morning">Buổi sáng</option><option value="afternoon">Buổi chiều</option></select></label><label><span>Đến ngày</span><input type="date" required value={form.endDate} onChange={event=>update("endDate",event.target.value)}/></label><label><span>Buổi kết thúc</span><select value={form.endDayPart} onChange={event=>update("endDayPart",event.target.value)}><option value="full_day">Cả ngày</option><option value="morning">Buổi sáng</option><option value="afternoon">Buổi chiều</option></select></label><label><span>Số ngày dự kiến</span><input readOnly value={estimate}/></label></div>{selectedType?.deductsBalance&&selectedBalance?<section className="leave-form-summary"><div><span>Còn lại chính thức</span><strong>{selectedBalance.officialRemaining}</strong></div><div><span>Đang chờ duyệt</span><strong>{selectedBalance.pending}</strong></div><div><span>Khả dụng</span><strong>{selectedBalance.availableAfterPending}</strong></div><div><span>Còn lại nếu duyệt</span><strong>{selectedBalance.availableAfterPending-estimate}</strong></div></section>:null}<label><span>Lý do</span><textarea required rows={5} maxLength={3000} value={form.reason} onChange={event=>update("reason",event.target.value)}/></label><label><span>Tài liệu đính kèm</span><input accept="application/pdf,image/png,image/jpeg" type="file" onChange={event=>setFile(event.target.files?.[0]??null)}/></label>{error?<p className="form-error">{error}</p>:null}<div className="form-actions"><Button disabled={busy} onClick={()=>void save(false)}>Lưu nháp</Button><Button disabled={busy} type="submit" variant="primary">Gửi duyệt</Button></div></form></Card>;
}
