export type InventoryDocumentType = "receipt" | "issue" | "transfer" | "adjustment" | "reversal";
export type InventoryDocumentStatus = "draft" | "submitted" | "posted" | "cancelled" | "reversed";

export interface UnitOfMeasure { id: string; code: string; name: string; symbol: string; active: boolean; }
export interface ItemCategory { id: string; code: string; name: string; parentId?: string; active: boolean; sortOrder: number; }
export interface Warehouse { id: string; code: string; name: string; type: "main" | "worksite" | "temporary" | "bonded"; address?: string; managerEmployeeId?: string; managerName?: string; projectId?: string; projectName?: string; worksiteId?: string; worksiteName?: string; status: "active" | "inactive"; note?: string; rowVersion: number; }
export interface InventoryItem { id: string; itemCode: string; name: string; shortName?: string; categoryId?: string; categoryName?: string; baseUomId: string; uomCode: string; uomName: string; specification?: string; brand?: string; manufacturer?: string; countryOfOrigin?: string; trackedInventory: boolean; status: "active" | "inactive"; note?: string; totalOnHand: number; rowVersion: number; balances?: InventoryBalance[]; }
export interface InventoryDocumentLine { id: string; itemId: string; itemCode: string; itemName: string; quantity: number; adjustmentQuantity?: number; uomId: string; uomCode: string; unitPrice?: number; expectedQuantity?: number; shipmentLineId?: string; reference?: string; purpose?: string; note?: string; rowVersion: number; }
export interface InventoryDocument { id: string; documentNumber: string; type: InventoryDocumentType; status: InventoryDocumentStatus; documentDate: string; postingDate?: string; sourceWarehouseId?: string; sourceWarehouseName?: string; targetWarehouseId?: string; targetWarehouseName?: string; transactionTypeCode: string; supplierReference?: string; shipmentId?: string; shipmentReceiptReference?: string; projectId?: string; projectName?: string; worksiteId?: string; worksiteName?: string; deliveredBy?: string; receivedBy?: string; recipient?: string; receivingDepartment?: string; note?: string; submittedAt?: string; postedAt?: string; postedByName?: string; reversedAt?: string; reversalDocumentId?: string; reversesDocumentId?: string; rowVersion: number; lines: InventoryDocumentLine[]; }
export interface InventoryBalance { warehouseId: string; warehouseCode: string; warehouseName: string; itemId: string; itemCode: string; itemName: string; categoryName?: string; uomCode: string; onHand: number; minimumStock?: number; status: "in_stock" | "low_stock" | "out_of_stock"; updatedAt: string; }
export interface StockLedgerEntry { id: string; sequence: number; warehouseId: string; warehouseName: string; itemId: string; itemCode: string; itemName: string; transactionType: InventoryDocumentType; documentId: string; documentNumber: string; transactionLineId: string; postingDate: string; quantityIn: number; quantityOut: number; signedQuantity: number; runningBalance: number; uomCode: string; projectName?: string; worksiteName?: string; reference?: string; postedByName?: string; createdAt: string; }
export interface StockCountLine { id: string; itemId: string; itemCode: string; itemName: string; uomCode: string; expectedQuantity: number; countedQuantity?: number; variance?: number; note?: string; }
export interface StockCount { id: string; countNumber: string; warehouseId: string; warehouseName: string; countDate: string; snapshotAt: string; status: "draft" | "counting" | "reviewed" | "posted" | "cancelled"; scope: "all" | "selected"; transactionPolicy: "freeze" | "reconcile"; note?: string; createdByName?: string; reviewedByName?: string; postedByName?: string; postedAt?: string; adjustmentDocumentId?: string; rowVersion: number; lines: StockCountLine[]; }
export interface WarehouseDashboard { itemCount: number; warehouseCount: number; outOfStock: number; lowStock: number; pendingDocuments: number; recentDocuments: InventoryDocument[]; lowStockItems: InventoryBalance[]; }
