import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import type { z } from "zod";

import type { leaveAdjustmentSchema, leaveGrantSchema, leavePolicyInputSchema, leaveRequestInputSchema, leaveRequestUpdateSchema, leaveTypeInputSchema, leaveWorkflowInputSchema } from "@/features/leave/schemas/leaveSchemas";
import { calculateLeaveDays, summarizeLedger, withPending } from "@/features/leave/services/leaveRules";
import type { LeaveApprovalStep, LeaveBalance, LeaveLedgerEntry, LeavePolicy, LeaveRequest, LeaveType } from "@/features/leave/types/leaveTypes";
import { AppError } from "@/lib/api/errors";
import { can, type AuthenticatedUser } from "@/lib/auth/permissions";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { recordAuditLog } from "@/services/audit/auditLog";

type Row = Record<string, unknown>;
interface Identity { accountId: string; employeeId: string; employeeCode: string; employeeName: string; departmentId: string; departmentName: string; positionName: string; managerEmployeeId?: string; }
const requestSelect = "*,leave_types(name,deducts_balance),leave_request_approval_steps(*),leave_request_attachments(id,file_name,created_at)";

function db() { const client=getSupabaseServiceClient(); if(!client) throw new AppError("SERVER_ERROR","Supabase chưa được cấu hình."); return client; }
function nested(row:Row,key:string):Row|undefined { const value=row[key]; return Array.isArray(value)?value[0] as Row|undefined:value&&typeof value==="object"?value as Row:undefined; }
function text(row:Row,key:string){const value=row[key]; return typeof value==="string"&&value?value:undefined;}
function required(row:Row,key:string){const value=text(row,key);if(!value)throw new AppError("SERVER_ERROR",`Dữ liệu thiếu ${key}.`);return value;}

async function identity(client:SupabaseClient,user:AuthenticatedUser):Promise<Identity>{
  let accountQuery=client.from("app_accounts").select("id,employee_id,status").limit(1);accountQuery=/^[0-9a-f-]{36}$/i.test(user.id)?accountQuery.eq("id",user.id):accountQuery.eq("primary_email",user.email);
  const {data:account,error}=await accountQuery.maybeSingle();if(error||!account?.employee_id||account.status!=="active")throw new AppError("PERMISSION_DENIED","Tài khoản chưa liên kết hồ sơ nhân viên.");
  const {data:employee,error:employeeError}=await client.from("employees").select("id,employee_code,full_name,department_id,position_id,manager_employee_id").eq("id",account.employee_id).single();
  if(employeeError||!employee)throw new AppError("SERVER_ERROR","Không thể đọc hồ sơ nhân viên.");
  const [{data:department},{data:position}]=await Promise.all([client.from("departments").select("name").eq("id",employee.department_id).maybeSingle(),client.from("positions").select("name").eq("id",employee.position_id).maybeSingle()]);
  return{accountId:String(account.id),employeeId:String(employee.id),employeeCode:employee.employee_code,employeeName:employee.full_name,departmentId:employee.department_id,departmentName:department?.name??"—",positionName:position?.name??"—",managerEmployeeId:employee.manager_employee_id??undefined};
}

function mapType(row:Row):LeaveType{return{id:required(row,"id"),code:required(row,"code"),name:required(row,"name"),tone:required(row,"tone") as LeaveType["tone"],deductsBalance:Boolean(row.deducts_balance),requiresReason:Boolean(row.requires_reason),requiresAttachment:Boolean(row.requires_attachment),allowsHalfDay:Boolean(row.allows_half_day),allowsMultiDay:Boolean(row.allows_multi_day),workflowId:required(row,"workflow_id"),active:Boolean(row.active)};}
function mapStep(row:Row):LeaveApprovalStep{return{id:required(row,"id"),stepOrder:Number(row.step_order),approverSource:required(row,"approver_source"),approverAccountId:text(row,"resolved_approver_account_id"),approverName:text(row,"resolved_approver_name"),status:required(row,"status") as LeaveApprovalStep["status"],actedAt:text(row,"acted_at"),comment:text(row,"comment")};}
function mapRequest(row:Row):LeaveRequest{const employee=(row.employee_snapshot??{}) as Row;const type=nested(row,"leave_types");return{id:required(row,"id"),requestNumber:required(row,"request_number"),employeeId:required(row,"employee_id"),employeeCode:text(employee,"employeeCode")??"—",employeeName:text(employee,"employeeName")??"—",departmentName:text(employee,"departmentName")??"—",positionName:text(employee,"positionName")??"—",leaveTypeId:required(row,"leave_type_id"),leaveTypeName:type?required(type,"name"):"—",deductsBalance:Boolean(type?.deducts_balance),startDate:required(row,"start_date"),endDate:required(row,"end_date"),startDayPart:required(row,"start_day_part") as LeaveRequest["startDayPart"],endDayPart:required(row,"end_day_part") as LeaveRequest["endDayPart"],calculatedDays:Number(row.calculated_days),reason:required(row,"reason"),status:required(row,"status") as LeaveRequest["status"],submittedAt:text(row,"submitted_at"),approvedAt:text(row,"approved_at"),rejectedAt:text(row,"rejected_at"),withdrawnAt:text(row,"withdrawn_at"),cancelledAt:text(row,"cancelled_at"),version:Number(row.version),createdAt:required(row,"created_at"),warnings:Array.isArray((row.request_snapshot as Row|undefined)?.warnings)?(row.request_snapshot as Row).warnings as string[]:[],approvalSteps:((row.leave_request_approval_steps??[]) as Row[]).map(mapStep).sort((a,b)=>a.stepOrder-b.stepOrder),attachments:((row.leave_request_attachments??[]) as Row[]).map(item=>({id:required(item,"id"),fileName:required(item,"file_name"),createdAt:required(item,"created_at")}))};}
function mapLedger(row:Row,typeName:string):LeaveLedgerEntry{return{id:required(row,"id"),employeeId:required(row,"employee_id"),leaveYear:Number(row.leave_year),leaveTypeId:required(row,"leave_type_id"),leaveTypeName:typeName,transactionType:required(row,"transaction_type") as LeaveLedgerEntry["transactionType"],amount:Number(row.amount),referenceType:required(row,"reference_type"),referenceId:required(row,"reference_id"),effectiveDate:required(row,"effective_date"),reason:required(row,"reason"),createdAt:required(row,"created_at")};}

export async function listLeaveTypes(activeOnly=false):Promise<LeaveType[]>{const {data,error}=await db().from("leave_types").select("*").order("name");if(error)throw new AppError("SERVER_ERROR","Không thể đọc loại nghỉ.");return(data??[]).filter(row=>!activeOnly||row.active).map(row=>mapType(row as Row));}
export async function getLeavePolicy():Promise<LeavePolicy>{const {data,error}=await db().from("leave_policies").select("*").eq("active",true).maybeSingle();if(error||!data)throw new AppError("SERVER_ERROR","Chưa có chính sách nghỉ.");return{weekendDays:data.weekend_days,allowNegativeBalance:data.allow_negative_balance,allowWithdrawPending:data.allow_withdraw_pending,cancellationRequiresApproval:data.cancellation_requires_approval,carryoverEnabled:data.carryover_enabled,carryoverMaxDays:Number(data.carryover_max_days)};}

async function calculatedDays(client:SupabaseClient,input:z.infer<typeof leaveRequestInputSchema>,type:LeaveType){
  if(input.startDate>input.endDate)throw new AppError("VALIDATION_ERROR","Khoảng ngày nghỉ không hợp lệ.");
  if(input.startDate!==input.endDate&&!type.allowsMultiDay)throw new AppError("VALIDATION_ERROR","Loại nghỉ này không cho phép nghỉ nhiều ngày.");
  if((input.startDayPart!=="full_day"||input.endDayPart!=="full_day")&&!type.allowsHalfDay)throw new AppError("VALIDATION_ERROR","Loại nghỉ này không cho phép nghỉ nửa ngày.");
  if(input.startDate===input.endDate&&input.startDayPart!==input.endDayPart)throw new AppError("VALIDATION_ERROR","Một ngày chỉ được chọn một hình thức nghỉ.");
  const policy=await getLeavePolicy();const {data:holidays}=await client.from("work_calendar_holidays").select("holiday_date").eq("active",true).gte("holiday_date",input.startDate).lte("holiday_date",input.endDate);
  const days=calculateLeaveDays({...input,weekendDays:policy.weekendDays,holidays:(holidays??[]).map(row=>row.holiday_date)});if(!days)throw new AppError("VALIDATION_ERROR","Khoảng đã chọn không có ngày làm việc.");return{days,policy};
}

export async function listLeaveRequests(user:AuthenticatedUser,scope:"self"|"all"|"approval"="self"):Promise<LeaveRequest[]>{const client=db();const actor=await identity(client,user);let query=client.from("leave_requests").select(requestSelect).order("created_at",{ascending:false}).limit(300);if(scope==="self")query=query.eq("employee_id",actor.employeeId);else if(scope==="approval"&&!can(user.permissions,"leave.approve_all")){const {data:steps}=await client.from("leave_request_approval_steps").select("request_id").eq("resolved_approver_account_id",actor.accountId).eq("status","pending");query=query.in("id",(steps??[]).map(row=>row.request_id));}else if(!can(user.permissions,"leave.view_all")&&!can(user.permissions,"leave.approve_all"))throw new AppError("PERMISSION_DENIED");const {data,error}=await query;if(error)throw new AppError("SERVER_ERROR","Không thể đọc danh sách đơn nghỉ.");return(data??[]).map(row=>mapRequest(row as Row));}

export async function getLeaveRequest(user:AuthenticatedUser,id:string):Promise<LeaveRequest>{const client=db();const actor=await identity(client,user);const {data,error}=await client.from("leave_requests").select(requestSelect).eq("id",id).maybeSingle();if(error||!data)throw new AppError("NOT_FOUND","Không tìm thấy đơn nghỉ.");const request=mapRequest(data as Row);const assigned=request.approvalSteps.some(step=>step.approverAccountId===actor.accountId);if(request.employeeId!==actor.employeeId&&!assigned&&!can(user.permissions,"leave.view_all")&&!can(user.permissions,"leave.approve_all"))throw new AppError("PERMISSION_DENIED");return request;}

export async function getLeaveOrganizationSnapshot(user:AuthenticatedUser,id:string):Promise<Row|undefined>{await getLeaveRequest(user,id);const {data}=await db().from("leave_requests").select("organization_snapshot").eq("id",id).maybeSingle();const snapshot=data?.organization_snapshot as Row|undefined;return snapshot&&typeof snapshot.organization==="object"?snapshot.organization as Row:undefined;}

export async function getLeaveRequestForPdf(user:AuthenticatedUser,id:string):Promise<LeaveRequest>{const client=db();const actor=await identity(client,user);const request=await getLeaveRequest(user,id);const own=request.employeeId===actor.employeeId;if(own?!can(user.permissions,"leave.pdf.export_self"):!can(user.permissions,"leave.pdf.export_all"))throw new AppError("PERMISSION_DENIED");await recordAuditLog({actorId:actor.accountId,action:"leave.pdf_exported",entityType:"leave_request",entityId:id,metadata:{requestNumber:request.requestNumber}});return request;}

export async function previewLeaveRequest(user:AuthenticatedUser,input:z.infer<typeof leaveRequestInputSchema>){const client=db();const actor=await identity(client,user);const type=(await listLeaveTypes()).find(item=>item.id===input.leaveTypeId&&item.active);if(!type)throw new AppError("VALIDATION_ERROR","Loại nghỉ không hoạt động.");const {days}=await calculatedDays(client,input,type);const balance=type.deductsBalance?await getEmployeeLeaveBalance(actor.employeeId,Number(input.startDate.slice(0,4)),type.id):undefined;return{days,balance};}

export async function getEmployeeLeaveBalance(employeeId:string,year:number,leaveTypeId:string):Promise<LeaveBalance>{
  const client=db();
  const [{data:employee,error:employeeError},{data:type,error:typeError},{data:ledger,error:ledgerError},{data:pending,error:pendingError}]=await Promise.all([
    client.from("employees").select("id,employee_code,full_name,department_id").eq("id",employeeId).single(),
    client.from("leave_types").select("id,name,deducts_balance").eq("id",leaveTypeId).single(),
    client.from("leave_ledger").select("*").eq("employee_id",employeeId).eq("leave_year",year).eq("leave_type_id",leaveTypeId),
    client.from("leave_requests").select("calculated_days").eq("employee_id",employeeId).eq("leave_type_id",leaveTypeId).in("status",["submitted","pending_approval"]).gte("start_date",`${year}-01-01`).lte("start_date",`${year}-12-31`)
  ]);
  if(employeeError||typeError||ledgerError||pendingError||!employee||!type)throw new AppError("SERVER_ERROR","Không thể tính số dư phép.");
  const {data:department}=await client.from("departments").select("name").eq("id",employee.department_id).maybeSingle();
  const entries=(ledger??[]).map(row=>mapLedger(row as Row,type.name));const summary=summarizeLedger(entries);
  return withPending({employeeId,employeeCode:employee.employee_code,employeeName:employee.full_name,departmentName:department?.name??"—",year,leaveTypeId,leaveTypeName:type.name,...summary},(pending??[]).reduce((sum,row)=>sum+Number(row.calculated_days),0));
}

export async function getMyLeaveBalances(user:AuthenticatedUser,year:number):Promise<{balances:LeaveBalance[];ledger:LeaveLedgerEntry[]}>{const client=db();const actor=await identity(client,user);const types=(await listLeaveTypes(true)).filter(type=>type.deductsBalance);const balances=await Promise.all(types.map(type=>getEmployeeLeaveBalance(actor.employeeId,year,type.id)));const {data}=await client.from("leave_ledger").select("*,leave_types(name)").eq("employee_id",actor.employeeId).eq("leave_year",year).order("effective_date",{ascending:false});return{balances,ledger:(data??[]).map(row=>mapLedger(row as Row,required(nested(row as Row,"leave_types")!,"name")))};}

export async function createLeaveRequest(user:AuthenticatedUser,input:z.infer<typeof leaveRequestInputSchema>):Promise<LeaveRequest>{if(!can(user.permissions,"leave.self.create"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await identity(client,user);const type=(await listLeaveTypes()).find(item=>item.id===input.leaveTypeId&&item.active);if(!type)throw new AppError("VALIDATION_ERROR","Loại nghỉ không hoạt động.");const {days,policy}=await calculatedDays(client,input,type);const {data:overlap}=await client.from("leave_requests").select("id").eq("employee_id",actor.employeeId).in("status",["draft","submitted","pending_approval","approved"]).lte("start_date",input.endDate).gte("end_date",input.startDate).limit(1);if(overlap?.length)throw new AppError("CONFLICT","Bạn đã có đơn nghỉ trong khoảng thời gian này.");if(type.deductsBalance){const balance=await getEmployeeLeaveBalance(actor.employeeId,Number(input.startDate.slice(0,4)),type.id);if(!policy.allowNegativeBalance&&balance.availableAfterPending<days)throw new AppError("CONFLICT","Số ngày phép không đủ.");}
  const {data:projects}=await client.from("project_assignments").select("id").eq("employee_id",actor.employeeId).eq("status","active").lte("start_date",input.endDate).or(`end_date.is.null,end_date.gte.${input.startDate}`);const warnings=projects?.length?["Có phân công dự án trong thời gian nghỉ."]:[];const snapshot={employeeCode:actor.employeeCode,employeeName:actor.employeeName,departmentName:actor.departmentName,positionName:actor.positionName};const {data,error}=await client.from("leave_requests").insert({employee_id:actor.employeeId,leave_type_id:type.id,start_date:input.startDate,end_date:input.endDate,start_day_part:input.startDayPart,end_day_part:input.endDayPart,calculated_days:days,reason:input.reason,employee_snapshot:snapshot,request_snapshot:{...input,calculatedDays:days,warnings},created_by:actor.accountId}).select("id").single();if(error||!data)throw new AppError("SERVER_ERROR","Không thể tạo đơn nghỉ.");await client.from("leave_domain_events").insert({event_type:"leave.draft_created",aggregate_id:data.id,payload:{employeeId:actor.employeeId}});await recordAuditLog({actorId:actor.accountId,action:"leave.draft_created",entityType:"leave_request",entityId:data.id,after:{days,status:"draft"}});return getLeaveRequest(user,data.id);}

export async function updateLeaveRequest(user:AuthenticatedUser,id:string,input:z.infer<typeof leaveRequestUpdateSchema>):Promise<LeaveRequest>{const client=db();const actor=await identity(client,user);const current=await getLeaveRequest(user,id);if(current.employeeId!==actor.employeeId||current.status!=="draft")throw new AppError("CONFLICT","Chỉ có thể sửa đơn nháp của chính bạn.");if(current.version!==input.version)throw new AppError("CONFLICT","Đơn đã được cập nhật ở nơi khác.");const type=(await listLeaveTypes()).find(item=>item.id===input.leaveTypeId&&item.active);if(!type)throw new AppError("VALIDATION_ERROR","Loại nghỉ không hoạt động.");const {days}=await calculatedDays(client,input,type);const {data,error}=await client.from("leave_requests").update({leave_type_id:type.id,start_date:input.startDate,end_date:input.endDate,start_day_part:input.startDayPart,end_day_part:input.endDayPart,calculated_days:days,reason:input.reason,request_snapshot:{...input,calculatedDays:days,warnings:current.warnings}}).eq("id",id).eq("version",input.version).select("id").maybeSingle();if(error||!data)throw new AppError("CONFLICT","Đơn đã được cập nhật ở nơi khác.");await recordAuditLog({actorId:actor.accountId,action:"leave.draft_updated",entityType:"leave_request",entityId:id});return getLeaveRequest(user,id);}

async function resolveApprover(client:SupabaseClient,source:string,config:Row,actor:Identity):Promise<{id?:string;name?:string}>{let employeeId:string|undefined;let accountId:string|undefined;if(source==="direct_manager")employeeId=actor.managerEmployeeId;else if(source==="department_manager"){const {data}=await client.from("departments").select("manager_employee_id").eq("id",actor.departmentId).single();employeeId=data?.manager_employee_id??undefined;}else if(source==="specific_user")accountId=text(config,"specific_account_id");else {const roleCode=source==="hr_role"?"hr":text(config,"specific_role_code");if(roleCode){const {data:role}=await client.from("roles").select("id").eq("code",roleCode).single();if(role){const {data:members}=await client.from("account_roles").select("account_id").eq("role_id",role.id).order("account_id").limit(10);accountId=members?.map(item=>item.account_id).find(id=>id!==actor.accountId)??members?.[0]?.account_id;}}}if(employeeId){const {data}=await client.from("app_accounts").select("id,display_name,status").eq("employee_id",employeeId).eq("status","active").maybeSingle();return{id:data?.id,name:data?.display_name};}if(accountId){const {data}=await client.from("app_accounts").select("id,display_name,status").eq("id",accountId).eq("status","active").maybeSingle();return{id:data?.id,name:data?.display_name};}return{};}

export async function submitLeaveRequest(user:AuthenticatedUser,id:string,version:number):Promise<LeaveRequest>{
  const client=db();const actor=await identity(client,user);const request=await getLeaveRequest(user,id);
  if(request.employeeId!==actor.employeeId||request.status!=="draft")throw new AppError("CONFLICT","Đơn không còn ở trạng thái nháp.");
  if(request.version!==version)throw new AppError("CONFLICT","Đơn đã được cập nhật ở nơi khác.");
  const type=(await listLeaveTypes()).find(item=>item.id===request.leaveTypeId&&item.active);if(!type)throw new AppError("CONFLICT","Loại nghỉ không còn hoạt động.");
  if(type.requiresAttachment&&!request.attachments.length)throw new AppError("VALIDATION_ERROR","Loại nghỉ này yêu cầu tài liệu đính kèm.");
  const validationInput={leaveTypeId:request.leaveTypeId,startDate:request.startDate,endDate:request.endDate,startDayPart:request.startDayPart,endDayPart:request.endDayPart,reason:request.reason};
  const {days,policy}=await calculatedDays(client,validationInput,type);if(days!==request.calculatedDays)throw new AppError("CONFLICT","Lịch làm việc đã thay đổi. Vui lòng cập nhật đơn.");
  const {data:overlap}=await client.from("leave_requests").select("id").eq("employee_id",actor.employeeId).neq("id",id).in("status",["submitted","pending_approval","approved"]).lte("start_date",request.endDate).gte("end_date",request.startDate).limit(1);if(overlap?.length)throw new AppError("CONFLICT","Bạn đã có đơn nghỉ trong khoảng thời gian này.");
  if(type.deductsBalance&&!policy.allowNegativeBalance){const balance=await getEmployeeLeaveBalance(actor.employeeId,Number(request.startDate.slice(0,4)),type.id);if(balance.availableAfterPending<days)throw new AppError("CONFLICT","Số ngày phép không đủ.");}
  const {data:workflow}=await client.from("leave_workflows").select("id,code,name,leave_workflow_steps(*)").eq("id",type.workflowId).eq("active",true).maybeSingle();if(!workflow)throw new AppError("CONFLICT","Chưa cấu hình quy trình duyệt.");
  const definitions=((workflow.leave_workflow_steps??[]) as Row[]).sort((a,b)=>Number(a.step_order)-Number(b.step_order));if(!definitions.length)throw new AppError("CONFLICT","Quy trình chưa có bước duyệt.");
  const steps=[];let missing=false;for(const definition of definitions){const approver=await resolveApprover(client,String(definition.approver_source),definition,actor);if(!approver.id)missing=true;steps.push({request_id:id,step_order:definition.step_order,approver_source:definition.approver_source,resolved_approver_account_id:approver.id??null,resolved_approver_name:approver.name??null,snapshot:{source:definition.approver_source,required:definition.required,approvalMode:definition.approval_mode}});}
  const snapshot={id:workflow.id,code:workflow.code,name:workflow.name,steps:steps.map(step=>step.snapshot)};const {data:claimed,error}=await client.from("leave_requests").update({status:missing?"submitted":"pending_approval",submitted_at:new Date().toISOString(),workflow_snapshot:snapshot}).eq("id",id).eq("version",version).select("id").maybeSingle();if(error||!claimed)throw new AppError("CONFLICT","Đơn đã được cập nhật ở nơi khác.");
  const {error:stepError}=await client.from("leave_request_approval_steps").insert(steps);if(stepError)throw new AppError("SERVER_ERROR","Không thể tạo các bước duyệt.");
  await client.from("leave_domain_events").insert([{event_type:"leave.submitted",aggregate_id:id,payload:{}},{event_type:missing?"leave.approver_missing":"leave.approval_required",aggregate_id:id,payload:{}}]);await recordAuditLog({actorId:actor.accountId,action:"leave.submitted",entityType:"leave_request",entityId:id,after:{status:missing?"submitted":"pending_approval"}});return getLeaveRequest(user,id);
}

export async function decideLeaveRequest(user:AuthenticatedUser,id:string,action:"approve"|"reject",comment?:string):Promise<LeaveRequest>{if(!can(user.permissions,"leave.approve")&&!can(user.permissions,"leave.approve_all"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await identity(client,user);const request=await getLeaveRequest(user,id);const pending=request.approvalSteps.find(step=>step.status==="pending");if(!pending) return request;if(pending.approverAccountId!==actor.accountId&&!can(user.permissions,"leave.approve_all"))throw new AppError("PERMISSION_DENIED");if(can(user.permissions,"leave.approve_all")&&pending.approverAccountId!==actor.accountId){await client.from("leave_request_approval_steps").update({resolved_approver_account_id:actor.accountId,resolved_approver_name:user.displayName,snapshot:{reassignedByAllScope:true}}).eq("id",pending.id);}
  const {error}=await client.rpc("process_leave_approval",{p_request_id:id,p_actor_id:actor.accountId,p_action:action,p_comment:comment??null});if(error){if(error.message.includes("APPROVER"))throw new AppError("PERMISSION_DENIED");if(error.message.includes("REJECT_REASON"))throw new AppError("VALIDATION_ERROR","Cần nhập lý do từ chối.");throw new AppError("CONFLICT","Đơn đã được người khác xử lý.");}await recordAuditLog({actorId:actor.accountId,action:action==="approve"?"leave.approved":"leave.rejected",entityType:"leave_request",entityId:id,reason:comment});return getLeaveRequest(user,id);}

export async function withdrawLeaveRequest(user:AuthenticatedUser,id:string,version:number):Promise<LeaveRequest>{if(!can(user.permissions,"leave.self.withdraw"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await identity(client,user);const request=await getLeaveRequest(user,id);if(request.employeeId!==actor.employeeId||!["submitted","pending_approval"].includes(request.status))throw new AppError("CONFLICT","Đơn không thể thu hồi.");const policy=await getLeavePolicy();if(!policy.allowWithdrawPending)throw new AppError("CONFLICT","Chính sách không cho phép thu hồi đơn đang duyệt.");const {data}=await client.from("leave_requests").update({status:"withdrawn",withdrawn_at:new Date().toISOString()}).eq("id",id).eq("version",version).select("id").maybeSingle();if(!data)throw new AppError("CONFLICT","Đơn đã được cập nhật ở nơi khác.");await client.from("leave_request_approval_steps").update({status:"cancelled"}).eq("request_id",id).eq("status","pending");await client.from("leave_domain_events").insert({event_type:"leave.withdrawn",aggregate_id:id,payload:{}});await recordAuditLog({actorId:actor.accountId,action:"leave.withdrawn",entityType:"leave_request",entityId:id});return getLeaveRequest(user,id);}

export async function cancelLeaveRequest(user:AuthenticatedUser,id:string,reason:string):Promise<LeaveRequest>{const client=db();const actor=await identity(client,user);const request=await getLeaveRequest(user,id);if(request.employeeId!==actor.employeeId&&!can(user.permissions,"leave.view_all"))throw new AppError("PERMISSION_DENIED");const policy=await getLeavePolicy();if(policy.cancellationRequiresApproval&&!can(user.permissions,"leave.approve_all"))throw new AppError("CONFLICT","Chính sách yêu cầu HR phê duyệt việc hủy đơn.");const {error}=await client.rpc("cancel_approved_leave",{p_request_id:id,p_actor_id:actor.accountId,p_reason:reason});if(error)throw new AppError("CONFLICT","Đơn không thể hủy hoặc đã được xử lý.");await recordAuditLog({actorId:actor.accountId,action:"leave.cancelled",entityType:"leave_request",entityId:id,reason});return getLeaveRequest(user,id);}

export async function postLeaveAdjustment(user:AuthenticatedUser,input:z.infer<typeof leaveAdjustmentSchema>):Promise<LeaveBalance>{if(!can(user.permissions,"leave.balance.adjust"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await identity(client,user);const transactionType=input.direction==="add"?"adjustment_add":"adjustment_subtract";const amount=input.direction==="add"?input.amount:-input.amount;const {error}=await client.from("leave_ledger").insert({employee_id:input.employeeId,leave_year:input.year,leave_type_id:input.leaveTypeId,transaction_type:transactionType,amount,reference_type:"hr_adjustment",reference_id:input.idempotencyKey,effective_date:input.effectiveDate,reason:input.reason,idempotency_key:input.idempotencyKey,created_by:actor.accountId});if(error&&error.code!=="23505")throw new AppError("SERVER_ERROR","Không thể điều chỉnh phép.");await recordAuditLog({actorId:actor.accountId,action:"leave.balance_adjusted",entityType:"leave_balance",entityId:`${input.employeeId}:${input.year}`,reason:input.reason,after:{amount,leaveTypeId:input.leaveTypeId}});return getEmployeeLeaveBalance(input.employeeId,input.year,input.leaveTypeId);}
export async function postLeaveGrant(user:AuthenticatedUser,input:z.infer<typeof leaveGrantSchema>):Promise<LeaveBalance[]>{if(!can(user.permissions,"leave.balance.adjust"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await identity(client,user);const rows=input.employeeIds.map(employeeId=>({employee_id:employeeId,leave_year:input.year,leave_type_id:input.leaveTypeId,transaction_type:"grant",amount:input.amount,reference_type:"grant_batch",reference_id:`${input.idempotencyKey}:${employeeId}`,effective_date:`${input.year}-01-01`,reason:input.reason,idempotency_key:input.idempotencyKey,created_by:actor.accountId}));const {error}=await client.from("leave_ledger").upsert(rows,{onConflict:"reference_type,reference_id,transaction_type,leave_type_id",ignoreDuplicates:true});if(error)throw new AppError("SERVER_ERROR","Không thể cấp phép.");await recordAuditLog({actorId:actor.accountId,action:"leave.balance_granted",entityType:"leave_grant_batch",entityId:input.idempotencyKey,after:{count:input.employeeIds.length,amount:input.amount}});return Promise.all(input.employeeIds.map(employeeId=>getEmployeeLeaveBalance(employeeId,input.year,input.leaveTypeId)));}

export async function listAllLeaveBalances(user:AuthenticatedUser,year:number):Promise<LeaveBalance[]>{if(!can(user.permissions,"leave.balance.view_all"))throw new AppError("PERMISSION_DENIED");const client=db();await identity(client,user);const {data:employees,error}=await client.from("employees").select("id").in("employment_status",["active","probation","pending_onboarding"]);if(error)throw new AppError("SERVER_ERROR","Không thể đọc nhân sự.");const types=(await listLeaveTypes(true)).filter(type=>type.deductsBalance);return(await Promise.all((employees??[]).flatMap(employee=>types.map(type=>getEmployeeLeaveBalance(employee.id,year,type.id))))).sort((a,b)=>a.employeeCode.localeCompare(b.employeeCode));}

export async function getEmployeeLeaveBalances(user:AuthenticatedUser,employeeId:string,year:number):Promise<LeaveBalance[]>{if(!can(user.permissions,"leave.balance.view_all"))throw new AppError("PERMISSION_DENIED");await identity(db(),user);const types=(await listLeaveTypes(true)).filter(type=>type.deductsBalance);return Promise.all(types.map(type=>getEmployeeLeaveBalance(employeeId,year,type.id)));}

export async function getEmployeeLeaveLedger(user:AuthenticatedUser,employeeId:string,year:number):Promise<LeaveLedgerEntry[]>{if(!can(user.permissions,"leave.balance.view_all"))throw new AppError("PERMISSION_DENIED");const client=db();await identity(client,user);const [types,{data,error}]=await Promise.all([listLeaveTypes(),client.from("leave_ledger").select("*").eq("employee_id",employeeId).eq("leave_year",year).order("effective_date",{ascending:false})]);if(error)throw new AppError("SERVER_ERROR","Không thể đọc sổ phép.");const names=new Map(types.map(type=>[type.id,type.name]));return(data??[]).map(row=>mapLedger(row as Row,names.get(row.leave_type_id)??"—"));}

export async function createLeaveType(user:AuthenticatedUser,input:z.infer<typeof leaveTypeInputSchema>):Promise<LeaveType>{if(!can(user.permissions,"leave.type.manage"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await identity(client,user);const {data,error}=await client.from("leave_types").insert({code:input.code,name:input.name,tone:input.tone,deducts_balance:input.deductsBalance,requires_reason:input.requiresReason,requires_attachment:input.requiresAttachment,allows_half_day:input.allowsHalfDay,allows_multi_day:input.allowsMultiDay,workflow_id:input.workflowId,active:input.active,created_by:actor.accountId}).select("*").single();if(error||!data)throw new AppError(error?.code==="23505"?"CONFLICT":"SERVER_ERROR",error?.code==="23505"?"Mã loại nghỉ đã tồn tại.":"Không thể tạo loại nghỉ.");await recordAuditLog({actorId:actor.accountId,action:"leave.type_created",entityType:"leave_type",entityId:data.id});return mapType(data as Row);}

export async function getApprovedLeaveForEmployeeDate(employeeId:string,date:string){const {data,error}=await db().from("leave_requests").select("id,request_number,leave_type_id,start_date,end_date,start_day_part,end_day_part,calculated_days,leave_types(name)").eq("employee_id",employeeId).eq("status","approved").lte("start_date",date).gte("end_date",date).maybeSingle();if(error)throw new AppError("SERVER_ERROR","Không thể kiểm tra nghỉ phép.");return data?{requestId:data.id,requestNumber:data.request_number,leaveTypeId:data.leave_type_id,leaveTypeName:required(nested(data as Row,"leave_types")!,"name"),dayPart:data.start_date===data.end_date?data.start_day_part:data.start_date===date?data.start_day_part:data.end_date===date?data.end_day_part:"full_day"}:undefined;}

export async function getApprovedLeaveForEmployeesDate(employeeIds:string[],date:string){if(!employeeIds.length)return new Map<string,{requestId:string;requestNumber:string;leaveTypeName:string;dayPart:string}>();const {data,error}=await db().from("leave_requests").select("id,employee_id,request_number,start_date,end_date,start_day_part,end_day_part,leave_types(name)").in("employee_id",employeeIds).eq("status","approved").lte("start_date",date).gte("end_date",date);if(error)throw new AppError("SERVER_ERROR","Không thể kiểm tra nghỉ phép.");return new Map((data??[]).map(row=>[row.employee_id,{requestId:row.id,requestNumber:row.request_number,leaveTypeName:required(nested(row as Row,"leave_types")!,"name"),dayPart:row.start_date===row.end_date?row.start_day_part:row.start_date===date?row.start_day_part:row.end_date===date?row.end_day_part:"full_day"}]));}

export async function updateLeaveType(user:AuthenticatedUser,id:string,input:z.infer<typeof leaveTypeInputSchema>):Promise<LeaveType>{if(!can(user.permissions,"leave.type.manage"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await identity(client,user);const {data,error}=await client.from("leave_types").update({code:input.code,name:input.name,tone:input.tone,deducts_balance:input.deductsBalance,requires_reason:input.requiresReason,requires_attachment:input.requiresAttachment,allows_half_day:input.allowsHalfDay,allows_multi_day:input.allowsMultiDay,workflow_id:input.workflowId,active:input.active}).eq("id",id).select("*").maybeSingle();if(error||!data)throw new AppError(error?.code==="23505"?"CONFLICT":"NOT_FOUND",error?.code==="23505"?"Mã loại nghỉ đã tồn tại.":"Không tìm thấy loại nghỉ.");await recordAuditLog({actorId:actor.accountId,action:"leave.type_updated",entityType:"leave_type",entityId:id,after:input});return mapType(data as Row);}

export async function listLeaveWorkflows(user:AuthenticatedUser){
  if(!can(user.permissions,"leave.workflow.manage")&&!can(user.permissions,"leave.self.create"))throw new AppError("PERMISSION_DENIED");
  const {data,error}=await db().from("leave_workflows").select("id,code,name,active,leave_workflow_steps(id,step_order,approver_source,specific_account_id,specific_role_code,required,approval_mode)").order("name");
  if(error)throw new AppError("SERVER_ERROR","Không thể đọc quy trình nghỉ.");
  return (data??[]).map(item=>({id:item.id,code:item.code,name:item.name,active:item.active,steps:(item.leave_workflow_steps??[]).sort((a,b)=>a.step_order-b.step_order).map(step=>({id:step.id,stepOrder:step.step_order,approverSource:step.approver_source,specificAccountId:step.specific_account_id??undefined,specificRoleCode:step.specific_role_code??undefined}))}));
}

export async function createLeaveWorkflow(user:AuthenticatedUser,input:z.infer<typeof leaveWorkflowInputSchema>){
  if(!can(user.permissions,"leave.workflow.manage"))throw new AppError("PERMISSION_DENIED");
  const client=db();const actor=await identity(client,user);
  const {data,error}=await client.from("leave_workflows").insert({code:input.code,name:input.name,active:input.active,created_by:actor.accountId}).select("id").single();
  if(error||!data)throw new AppError(error?.code==="23505"?"CONFLICT":"SERVER_ERROR",error?.code==="23505"?"Mã quy trình đã tồn tại.":"Không thể tạo quy trình.");
  const {error:stepError}=await client.from("leave_workflow_steps").insert(input.steps.map((step,index)=>({workflow_id:data.id,step_order:index+1,approver_source:step.approverSource,specific_account_id:step.specificAccountId??null,specific_role_code:step.specificRoleCode??null})));
  if(stepError){await client.from("leave_workflows").delete().eq("id",data.id);throw new AppError("SERVER_ERROR","Không thể tạo bước duyệt.");}
  await recordAuditLog({actorId:actor.accountId,action:"leave.workflow_created",entityType:"leave_workflow",entityId:data.id});
  return (await listLeaveWorkflows(user)).find(item=>item.id===data.id)!;
}

export async function updateLeaveWorkflow(user:AuthenticatedUser,id:string,input:z.infer<typeof leaveWorkflowInputSchema>){if(!can(user.permissions,"leave.workflow.manage"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await identity(client,user);const {data,error}=await client.from("leave_workflows").update({code:input.code,name:input.name,active:input.active}).eq("id",id).select("id").maybeSingle();if(error||!data)throw new AppError(error?.code==="23505"?"CONFLICT":"NOT_FOUND",error?.code==="23505"?"Mã quy trình đã tồn tại.":"Không tìm thấy quy trình.");const {error:deleteError}=await client.from("leave_workflow_steps").delete().eq("workflow_id",id);if(deleteError)throw new AppError("SERVER_ERROR","Không thể cập nhật bước duyệt.");const {error:stepError}=await client.from("leave_workflow_steps").insert(input.steps.map((step,index)=>({workflow_id:id,step_order:index+1,approver_source:step.approverSource,specific_account_id:step.specificAccountId??null,specific_role_code:step.specificRoleCode??null})));if(stepError)throw new AppError("SERVER_ERROR","Không thể cập nhật bước duyệt.");await recordAuditLog({actorId:actor.accountId,action:"leave.workflow_updated",entityType:"leave_workflow",entityId:id,after:{code:input.code,name:input.name,active:input.active,stepCount:input.steps.length}});return(await listLeaveWorkflows(user)).find(item=>item.id===id)!;}

export async function updateLeavePolicy(user:AuthenticatedUser,input:z.infer<typeof leavePolicyInputSchema>):Promise<LeavePolicy>{
  if(!can(user.permissions,"leave.policy.manage"))throw new AppError("PERMISSION_DENIED");
  const client=db();const actor=await identity(client,user);
  const {data:current}=await client.from("leave_policies").select("id").eq("active",true).maybeSingle();
  if(!current)throw new AppError("NOT_FOUND","Chưa có chính sách nghỉ đang áp dụng.");
  const {error}=await client.from("leave_policies").update({weekend_days:input.weekendDays,allow_negative_balance:input.allowNegativeBalance,allow_withdraw_pending:input.allowWithdrawPending,cancellation_requires_approval:input.cancellationRequiresApproval,carryover_enabled:input.carryoverEnabled,carryover_max_days:input.carryoverMaxDays}).eq("id",current.id);
  if(error)throw new AppError("SERVER_ERROR","Không thể lưu chính sách nghỉ.");
  await recordAuditLog({actorId:actor.accountId,action:"leave.policy_updated",entityType:"leave_policy",entityId:current.id,after:input});
  return getLeavePolicy();
}

function attachmentExtension(mime:string){return mime==="application/pdf"?"pdf":mime==="image/png"?"png":"jpg";}
async function validateLeaveAttachment(file:File){
  if(!["application/pdf","image/png","image/jpeg"].includes(file.type)||file.size<=0||file.size>5*1024*1024)throw new AppError("VALIDATION_ERROR","Chỉ nhận PDF, PNG, JPG tối đa 5 MB.");
  const bytes=new Uint8Array(await file.arrayBuffer());
  const valid=file.type==="application/pdf"?new TextDecoder().decode(bytes.slice(0,5))==="%PDF-":file.type==="image/png"?bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47:bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;
  if(!valid)throw new AppError("VALIDATION_ERROR","Nội dung tệp không đúng định dạng.");return bytes;
}

export async function uploadLeaveAttachment(user:AuthenticatedUser,requestId:string,file:File){
  const client=db();const actor=await identity(client,user);const request=await getLeaveRequest(user,requestId);
  if(request.employeeId!==actor.employeeId||request.status!=="draft")throw new AppError("CONFLICT","Chỉ có thể đính kèm vào đơn nháp của bạn.");
  const bytes=await validateLeaveAttachment(file);const assetId=crypto.randomUUID();const path=`${new Date().getFullYear()}/${requestId}/${assetId}.${attachmentExtension(file.type)}`;
  const {error:uploadError}=await client.storage.from("leave-attachments").upload(path,bytes,{contentType:file.type,upsert:false});if(uploadError)throw new AppError("SERVER_ERROR","Không thể tải tệp lên.");
  const safeName=file.name.replace(/[\\/:*?"<>|]/g,"_").slice(0,180)||`tai-lieu.${attachmentExtension(file.type)}`;
  const {error:assetError}=await client.from("file_assets").insert({id:assetId,bucket:"leave-attachments",object_path:path,owner_entity_type:"leave_request",owner_entity_id:requestId,mime_type:file.type,byte_size:file.size,created_by:actor.accountId});
  if(assetError){await client.storage.from("leave-attachments").remove([path]);throw new AppError("SERVER_ERROR","Không thể lưu tệp đính kèm.");}
  const {data,error}=await client.from("leave_request_attachments").insert({request_id:requestId,file_id:assetId,file_name:safeName}).select("id,created_at").single();
  if(error||!data){await client.storage.from("leave-attachments").remove([path]);throw new AppError("SERVER_ERROR","Không thể liên kết tệp đính kèm.");}
  await client.from("leave_requests").update({updated_at:new Date().toISOString()}).eq("id",requestId);
  await recordAuditLog({actorId:actor.accountId,action:"leave.attachment_uploaded",entityType:"leave_request",entityId:requestId,after:{fileName:safeName,mimeType:file.type,byteSize:file.size}});
  return{id:data.id,fileName:safeName,createdAt:data.created_at};
}

export async function getLeaveAttachmentAsset(user:AuthenticatedUser,requestId:string,attachmentId:string){
  await getLeaveRequest(user,requestId);const {data,error}=await db().from("leave_request_attachments").select("file_name,file_assets!leave_request_attachments_file_id_fkey(bucket,object_path,mime_type)").eq("id",attachmentId).eq("request_id",requestId).maybeSingle();
  if(error||!data)throw new AppError("NOT_FOUND","Không tìm thấy tệp đính kèm.");const asset=nested(data as Row,"file_assets");if(!asset)throw new AppError("NOT_FOUND");return{fileName:data.file_name,bucket:required(asset,"bucket"),path:required(asset,"object_path"),mimeType:required(asset,"mime_type")};
}
