import {createHash} from "node:crypto";import {mkdir,readFile,writeFile} from "node:fs/promises";import {basename,extname,join} from "node:path";
const source=process.argv.find(value=>!value.startsWith("--")&&value!==process.argv[0]&&value!==process.argv[1]);const type=process.argv.find(value=>value.startsWith("--type="))?.slice(7);
if(!source||!type)throw new Error("Dùng: npm run migration:dry-run -- <file.json|file.csv> --type=employees");
const raw=await readFile(source);const checksum=createHash("sha256").update(raw).digest("hex");let rows;
if(extname(source).toLowerCase()===".json")rows=JSON.parse(raw.toString("utf8"));else{const lines=raw.toString("utf8").replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);const headers=lines.shift()?.split(",").map(x=>x.trim())||[];rows=lines.map(line=>Object.fromEntries(line.split(",").map((value,index)=>[headers[index],value.trim()])));}
if(!Array.isArray(rows))throw new Error("Nguồn phải là một mảng bản ghi.");
const keyByType={employees:"employee_code",departments:"code",positions:"code",projects:"code",warehouses:"code",inventory_items:"item_code"};const key=keyByType[type];if(!key)throw new Error(`Loại migration chưa hỗ trợ: ${type}`);
const seen=new Set(),errors=[];rows.forEach((row,index)=>{if(!row||typeof row!=="object")errors.push({row:index+2,code:"INVALID_ROW"});else{const value=String(row[key]||"").trim();if(!value)errors.push({row:index+2,field:key,code:"REQUIRED"});else if(seen.has(value))errors.push({row:index+2,field:key,code:"DUPLICATE_SOURCE_KEY",sourceKey:value});else seen.add(value);}});
const report={mode:"dry_run",source:basename(source),sourceChecksum:checksum,entityType:type,rowsTotal:rows.length,rowsValid:rows.length-errors.length,rowsInvalid:errors.length,errors,generatedAt:new Date().toISOString()};
await mkdir(join(process.cwd(),"artifacts","migration"),{recursive:true});const output=join(process.cwd(),"artifacts","migration",`${type}-${checksum.slice(0,12)}.json`);await writeFile(output,JSON.stringify(report,null,2),{flag:"wx"}).catch(async error=>{if(error.code!=="EEXIST")throw error;});console.log(JSON.stringify({...report,errors:errors.slice(0,20),reportPath:output},null,2));if(errors.length)process.exitCode=2;
