export type TimesheetPeriodStatus="open"|"reviewing"|"locked"|"reopened";
export type TimesheetDailyStatus="full_work"|"late"|"early_leave"|"missing_check_in"|"missing_check_out"|"annual_leave"|"unpaid_leave"|"absent"|"business_trip"|"holiday"|"rest_day"|"worker_site"|"needs_review";
export type TimesheetSource="SELF_ATTENDANCE"|"SUPERVISOR_ROSTER"|"APPROVED_LEAVE"|"MANUAL_ADJUSTMENT"|"SYSTEM_CALENDAR";
export type TimesheetExceptionType="missing_check_in"|"missing_check_out"|"attendance_leave_conflict"|"gps_issue"|"photo_pending"|"offline_sync_pending"|"worker_roster_conflict"|"duplicate_source_conflict";
export type TimesheetAdjustmentType="add_missing_check_in"|"add_missing_check_out"|"adjust_effective_time"|"mark_leave"|"mark_business_trip"|"correct_status"|"correct_work_fraction"|"note_only"|"other";

export interface Shift{ id:string;code:string;name:string;startTime:string;endTime:string;breakMinutes:number;lateGraceMinutes:number;earlyLeaveGraceMinutes:number;checkInEarliestMinutes:number;checkInLatestMinutes:number;checkOutEarliestMinutes:number;checkOutLatestMinutes:number;crossMidnight:boolean;active:boolean; }
export interface CalendarDay{ id:string;date:string;name:string;dayType:"holiday"|"company_holiday"|"makeup_workday"|"special";scopeType:"company"|"department"|"project"|"employee";scopeId?:string;isWorkingDay:boolean;active:boolean; }
export interface TimesheetEventInput{id:string;eventType:"check_in"|"check_out";effectiveAt:string;geofenceStatus:string;photoStatus:string;syncStatus:string;locationName?:string;photoId?:string;}
export interface TimesheetWorkerInput{status:"present"|"absent"|"leave"|"late"|"transferred"|"unconfirmed";dayException?:string;projectName?:string;worksiteName?:string;sessionId?:string;}
export interface TimesheetLeaveInput{requestId:string;requestNumber:string;typeCode:string;typeName:string;deductsBalance:boolean;fraction:number;}
export interface TimesheetAdjustment{ id:string;periodId:string;employeeId:string;workDate:string;adjustmentType:TimesheetAdjustmentType;effectiveTime?:string;correctedStatus?:TimesheetDailyStatus;correctedWorkFraction?:number;hrNote?:string;reason:string;createdByName?:string;createdAt:string;before:Record<string,unknown>;after:Record<string,unknown>; }
export interface DailyTimesheet{ id:string;periodId:string;employeeId:string;employeeCode:string;employeeName:string;departmentName:string;positionName:string;employmentTypeName:string;workDate:string;shiftId?:string;shiftName?:string;shiftStart?:string;shiftEnd?:string;sources:TimesheetSource[];effectiveCheckIn?:string;effectiveCheckOut?:string;workMinutes:number;workFraction:number;leaveFraction:number;lateMinutes:number;earlyLeaveMinutes:number;leaveTypeCode?:string;leaveTypeName?:string;status:TimesheetDailyStatus;hrNote?:string;exceptionCount:number;rawSource:Record<string,unknown>;adjustments:TimesheetAdjustment[];calculationVersion:number; }
export interface TimesheetSummary{ id:string;periodId:string;employeeId:string;employeeCode:string;employeeName:string;departmentName:string;positionName:string;employmentTypeName:string;scheduledWorkdays:number;actualWorkdays:number;workedMinutes:number;lateDays:number;lateMinutes:number;earlyLeaveDays:number;earlyLeaveMinutes:number;annualLeaveDays:number;unpaidLeaveDays:number;absentDays:number;businessTripDays:number;holidayDays:number;missingCheckInDays:number;missingCheckOutDays:number;exceptionCount:number; }
export interface TimesheetPeriod{id:string;code:string;name:string;startDate:string;endDate:string;status:TimesheetPeriodStatus;version:number;rowVersion:number;lockedAt?:string;reopenedAt?:string;reopenReason?:string;summaries?:TimesheetSummary[];}
export interface TimesheetException{id:string;periodId:string;dailyTimesheetId:string;employeeId:string;employeeCode:string;employeeName:string;workDate:string;type:TimesheetExceptionType;severity:"warning"|"high";status:"open"|"resolved"|"ignored";details:Record<string,unknown>;resolutionNote?:string;}

export type ReportType="timesheet"|"employee_list"|"employee_profile";
export interface ReportSheetDefinition{key:string;name:string;enabled:boolean;columns?:Array<{key:string;label:string;enabled:boolean;order:number}>;}
export interface ReportTemplate{id:string;code:string;name:string;reportType:ReportType;definition:{freezeHeader:boolean;autoFilter:boolean;includeBranding?:boolean;sheets:ReportSheetDefinition[]};version:number;active:boolean;}
export interface ReportExport{id:string;reportType:ReportType;templateId:string;templateVersion:number;periodId?:string;periodVersion?:number;status:"queued"|"processing"|"completed"|"failed";requestedAt:string;completedAt?:string;fileId?:string;fileName?:string;errorMessage?:string;}
