import type { CalendarDay, DailyTimesheet, Shift, TimesheetAdjustment, TimesheetDailyStatus, TimesheetEventInput, TimesheetExceptionType, TimesheetLeaveInput, TimesheetSource, TimesheetWorkerInput } from "@/features/timesheets/types/timesheetTypes";

const MINUTE=60_000;
export function minutesOfDay(value:string,timeZone="Asia/Ho_Chi_Minh"){const parts=new Intl.DateTimeFormat("en-GB",{timeZone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));return Number(parts.find(p=>p.type==="hour")?.value)*60+Number(parts.find(p=>p.type==="minute")?.value);}
export function scheduledMinutes(shift:Shift){const [sh,sm]=shift.startTime.slice(0,5).split(":").map(Number);const [eh,em]=shift.endTime.slice(0,5).split(":").map(Number);let result=eh*60+em-(sh*60+sm);if(shift.crossMidnight||result<=0)result+=1440;return Math.max(0,result-shift.breakMinutes);}
export function resolveShift<T extends {scopeType:"company"|"department"|"project"|"employee";scopeId?:string;effectiveFrom:string;effectiveTo?:string;weekdays:number[];shift:Shift}>(input:{assignments:T[];date:string;employeeId:string;departmentId:string;projectIds:string[]}):Shift|undefined{const day=new Date(`${input.date}T12:00:00Z`).getUTCDay();const rank={company:1,department:2,project:3,employee:4};return input.assignments.filter(item=>item.effectiveFrom<=input.date&&(!item.effectiveTo||item.effectiveTo>=input.date)&&item.weekdays.includes(day)&&(item.scopeType==="company"||item.scopeType==="employee"&&item.scopeId===input.employeeId||item.scopeType==="department"&&item.scopeId===input.departmentId||item.scopeType==="project"&&!!item.scopeId&&input.projectIds.includes(item.scopeId))).sort((a,b)=>rank[b.scopeType]-rank[a.scopeType])[0]?.shift;}
export function resolveCalendarDay<T extends CalendarDay>(items:T[],input:{date:string;employeeId:string;departmentId:string;projectIds:string[]}):T|undefined{const rank={company:1,department:2,project:3,employee:4};return items.filter(item=>item.active&&item.date===input.date&&(item.scopeType==="company"||item.scopeType==="employee"&&item.scopeId===input.employeeId||item.scopeType==="department"&&item.scopeId===input.departmentId||item.scopeType==="project"&&!!item.scopeId&&input.projectIds.includes(item.scopeId))).sort((a,b)=>rank[b.scopeType]-rank[a.scopeType])[0];}

export interface ComputeDailyInput{periodId:string;employee:{id:string;code:string;name:string;departmentName:string;positionName:string;employmentTypeName:string};date:string;shift?:Shift;calendarDay?:CalendarDay;events:TimesheetEventInput[];worker?:TimesheetWorkerInput;leave?:TimesheetLeaveInput;adjustments:TimesheetAdjustment[];}
export interface ComputedDaily extends Omit<DailyTimesheet,"id">{exceptions:Array<{type:TimesheetExceptionType;severity:"warning"|"high";details:Record<string,unknown>}>;}
export function computeDailyTimesheet(input:ComputeDailyInput):ComputedDaily{
  const events=[...input.events].sort((a,b)=>a.effectiveAt.localeCompare(b.effectiveAt));let effectiveIn=events.find(e=>e.eventType==="check_in")?.effectiveAt;let effectiveOut=[...events].reverse().find(e=>e.eventType==="check_out")?.effectiveAt;
  let statusOverride:TimesheetDailyStatus|undefined;let workOverride:number|undefined;let hrNote:string|undefined;let markLeave=false;
  for(const adjustment of input.adjustments){if(adjustment.adjustmentType==="add_missing_check_in")effectiveIn=adjustment.effectiveTime;if(adjustment.adjustmentType==="add_missing_check_out")effectiveOut=adjustment.effectiveTime;if(adjustment.adjustmentType==="correct_status"||adjustment.adjustmentType==="mark_business_trip")statusOverride=adjustment.correctedStatus??(adjustment.adjustmentType==="mark_business_trip"?"business_trip":undefined);if(adjustment.adjustmentType==="mark_leave"){markLeave=true;statusOverride=adjustment.correctedStatus??"annual_leave";}if(adjustment.adjustmentType==="correct_work_fraction")workOverride=adjustment.correctedWorkFraction;if(adjustment.hrNote)hrNote=adjustment.hrNote;}
  const sources=new Set<TimesheetSource>();if(events.length)sources.add("SELF_ATTENDANCE");if(input.worker)sources.add("SUPERVISOR_ROSTER");if(input.leave)sources.add("APPROVED_LEAVE");if(input.adjustments.length)sources.add("MANUAL_ADJUSTMENT");sources.add("SYSTEM_CALENDAR");
  const exceptions:Array<{type:TimesheetExceptionType;severity:"warning"|"high";details:Record<string,unknown>}>=[];if(input.leave&&events.length)exceptions.push({type:"attendance_leave_conflict",severity:"high",details:{requestNumber:input.leave.requestNumber,eventCount:events.length}});
  for(const event of events){if(["outside","accuracy_low","unavailable"].includes(event.geofenceStatus))exceptions.push({type:"gps_issue",severity:"warning",details:{eventId:event.id,status:event.geofenceStatus}});if(["pending_upload","upload_failed"].includes(event.photoStatus))exceptions.push({type:"photo_pending",severity:"warning",details:{eventId:event.id}});if(event.syncStatus!=="synced")exceptions.push({type:"offline_sync_pending",severity:"warning",details:{eventId:event.id,status:event.syncStatus}});}
  const workingDay=input.calendarDay?.isWorkingDay??Boolean(input.shift);let workMinutes=0;
  let opened:TimesheetEventInput|undefined;for(const event of events){if(event.eventType==="check_in"&&!opened)opened=event;else if(event.eventType==="check_out"&&opened){workMinutes+=Math.max(0,Math.round((new Date(event.effectiveAt).getTime()-new Date(opened.effectiveAt).getTime())/MINUTE));opened=undefined;}}
  if(events.filter(e=>e.eventType==="check_in").length===1&&events.filter(e=>e.eventType==="check_out").length===1&&input.shift)workMinutes=Math.max(0,workMinutes-input.shift.breakMinutes);
  let lateMinutes=0,earlyLeaveMinutes=0;if(input.shift&&effectiveIn){const start=input.shift.startTime.slice(0,5).split(":").map(Number);lateMinutes=Math.max(0,minutesOfDay(effectiveIn)-(start[0]*60+start[1])-input.shift.lateGraceMinutes);}if(input.shift&&effectiveOut){const end=input.shift.endTime.slice(0,5).split(":").map(Number);let actual=minutesOfDay(effectiveOut);const target=end[0]*60+end[1];if(input.shift.crossMidnight&&actual<720)actual+=1440;earlyLeaveMinutes=Math.max(0,target+(input.shift.crossMidnight?1440:0)-actual-input.shift.earlyLeaveGraceMinutes);}
  const leaveFraction=markLeave?1:(input.leave?.fraction??0);let workFraction=input.shift?Math.min(1,workMinutes/Math.max(1,scheduledMinutes(input.shift))):0;if(input.worker?.status==="present"||input.worker?.status==="late")workFraction=input.worker.dayException==="half_day"?.5:1;if(input.worker?.status==="absent")workFraction=0;if(workOverride!==undefined)workFraction=workOverride;
  if(workingDay&&!effectiveIn&&effectiveOut)exceptions.push({type:"missing_check_in",severity:"high",details:{}});if(workingDay&&((effectiveIn&&!effectiveOut)||opened))exceptions.push({type:"missing_check_out",severity:"high",details:{unpairedCheckInId:opened?.id}});if(input.worker?.status==="unconfirmed")exceptions.push({type:"worker_roster_conflict",severity:"high",details:{sessionId:input.worker.sessionId}});
  let status:TimesheetDailyStatus;if(statusOverride)status=statusOverride;else if(exceptions.some(e=>e.type==="attendance_leave_conflict"))status="needs_review";else if(!workingDay)status=input.calendarDay?.dayType==="holiday"||input.calendarDay?.dayType==="company_holiday"?"holiday":"rest_day";else if(input.leave&&leaveFraction>=1)status=input.leave.deductsBalance?"annual_leave":"unpaid_leave";else if(exceptions.some(e=>e.type==="missing_check_in"))status="missing_check_in";else if(exceptions.some(e=>e.type==="missing_check_out"))status="missing_check_out";else if(input.worker?.status==="absent")status="absent";else if(lateMinutes>0)status="late";else if(earlyLeaveMinutes>0)status="early_leave";else if(input.worker&&(input.worker.status==="present"||input.worker.status==="late"))status="worker_site";else if(effectiveIn&&effectiveOut)status="full_work";else if(input.leave)status=input.leave.deductsBalance?"annual_leave":"unpaid_leave";else status="absent";
  return{periodId:input.periodId,employeeId:input.employee.id,employeeCode:input.employee.code,employeeName:input.employee.name,departmentName:input.employee.departmentName,positionName:input.employee.positionName,employmentTypeName:input.employee.employmentTypeName,workDate:input.date,shiftId:input.shift?.id,shiftName:input.shift?.name,shiftStart:input.shift?.startTime,shiftEnd:input.shift?.endTime,sources:[...sources],effectiveCheckIn:effectiveIn,effectiveCheckOut:effectiveOut,workMinutes,workFraction:Number(workFraction.toFixed(2)),leaveFraction,lateMinutes,earlyLeaveMinutes,leaveTypeCode:input.leave?.typeCode,leaveTypeName:input.leave?.typeName,status,hrNote,exceptionCount:exceptions.length,rawSource:{events,worker:input.worker,leave:input.leave,calendar:input.calendarDay},adjustments:input.adjustments,calculationVersion:1,exceptions};
}
