import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import { AppError } from "@/lib/api/errors";
import { can, type AuthenticatedUser } from "@/lib/auth/permissions";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { recordAuditLog } from "@/services/audit/auditLog";
import { computeDailyTimesheet, resolveCalendarDay, resolveShift } from "./timesheetRules";
import type { CalendarDay, DailyTimesheet, Shift, TimesheetAdjustment, TimesheetException, TimesheetPeriod, TimesheetSummary } from "../types/timesheetTypes";

type Row = Record<string, unknown>;
type ShiftInput = Omit<Shift, "id"> & { id?: string };
type CalendarInput = Omit<CalendarDay, "id"> & { id?: string };

function db(): SupabaseClient { const value=getSupabaseServiceClient();if(!value)throw new AppError("SERVER_ERROR","Supabase chưa được cấu hình.");return value; }
function text(row:Row,key:string,fallback=""){const value=row[key];return typeof value==="string"?value:fallback;}
function optional(row:Row,key:string){const value=row[key];return typeof value==="string"&&value?value:undefined;}
function number(row:Row,key:string){return Number(row[key]??0);}
function requireAny(user:AuthenticatedUser,permissions:Parameters<typeof can>[1][]){if(!permissions.some(permission=>can(user.permissions,permission)))throw new AppError("PERMISSION_DENIED");}
async function actorId(client:SupabaseClient,user:AuthenticatedUser){let query=client.from("app_accounts").select("id").limit(1);query=/^[0-9a-f-]{36}$/i.test(user.id)?query.eq("id",user.id):query.eq("primary_email",user.email);const {data}=await query.maybeSingle();if(!data?.id)throw new AppError("PERMISSION_DENIED","Không tìm thấy tài khoản vận hành.");return String(data.id);}
async function visibleEmployeeIds(client:SupabaseClient,user:AuthenticatedUser){if(can(user.permissions,"timesheet.view_all"))return undefined;let query=client.from("app_accounts").select("employee_id").limit(1);query=/^[0-9a-f-]{36}$/i.test(user.id)?query.eq("id",user.id):query.eq("primary_email",user.email);const {data}=await query.maybeSingle();if(!data?.employee_id)throw new AppError("PERMISSION_DENIED","Tài khoản chưa liên kết nhân viên.");const own=String(data.employee_id);if(!can(user.permissions,"timesheet.view_team"))return[own];const {data:reports,error}=await client.from("employees").select("id").eq("manager_employee_id",own);if(error)throw new AppError("SERVER_ERROR","Không thể xác định phạm vi đội nhóm.");return[own,...(reports??[]).map(item=>String(item.id))];}
function dates(from:string,to:string){const result:string[]=[];const cursor=new Date(`${from}T00:00:00Z`);const end=new Date(`${to}T00:00:00Z`);while(cursor<=end){result.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1);if(result.length>93)throw new AppError("VALIDATION_ERROR","Một kỳ công không được dài quá 93 ngày.");}return result;}

function mapShift(row:Row):Shift{return{id:text(row,"id"),code:text(row,"code"),name:text(row,"name"),startTime:text(row,"start_time").slice(0,5),endTime:text(row,"end_time").slice(0,5),breakMinutes:number(row,"break_minutes"),lateGraceMinutes:number(row,"late_grace_minutes"),earlyLeaveGraceMinutes:number(row,"early_leave_grace_minutes"),checkInEarliestMinutes:number(row,"check_in_earliest_minutes"),checkInLatestMinutes:number(row,"check_in_latest_minutes"),checkOutEarliestMinutes:number(row,"check_out_earliest_minutes"),checkOutLatestMinutes:number(row,"check_out_latest_minutes"),crossMidnight:Boolean(row.cross_midnight),active:Boolean(row.active)};}
function mapPeriod(row:Row):TimesheetPeriod{return{id:text(row,"id"),code:text(row,"code"),name:text(row,"name"),startDate:text(row,"start_date"),endDate:text(row,"end_date"),status:text(row,"status") as TimesheetPeriod["status"],version:number(row,"version"),rowVersion:number(row,"row_version"),lockedAt:optional(row,"locked_at"),reopenedAt:optional(row,"reopened_at"),reopenReason:optional(row,"reopen_reason")};}
function mapDaily(row:Row):DailyTimesheet{const employee=(row.employee_snapshot??{}) as Row;const shift=(row.shift_snapshot??{}) as Row;return{id:text(row,"id"),periodId:text(row,"period_id"),employeeId:text(row,"employee_id"),employeeCode:text(employee,"code"),employeeName:text(employee,"name"),departmentName:text(employee,"departmentName"),positionName:text(employee,"positionName"),employmentTypeName:text(employee,"employmentTypeName"),workDate:text(row,"work_date"),shiftId:optional(row,"shift_id"),shiftName:optional(shift,"name"),shiftStart:optional(shift,"startTime"),shiftEnd:optional(shift,"endTime"),sources:Array.isArray(row.source_codes)?row.source_codes as DailyTimesheet["sources"]:[],effectiveCheckIn:optional(row,"effective_check_in"),effectiveCheckOut:optional(row,"effective_check_out"),workMinutes:number(row,"work_minutes"),workFraction:number(row,"work_fraction"),leaveFraction:number(row,"leave_fraction"),lateMinutes:number(row,"late_minutes"),earlyLeaveMinutes:number(row,"early_leave_minutes"),leaveTypeCode:optional(row,"leave_type_code"),leaveTypeName:optional(row,"leave_type_name"),status:text(row,"status") as DailyTimesheet["status"],hrNote:optional(row,"hr_note"),exceptionCount:number(row,"exception_count"),rawSource:(row.raw_source_snapshot??{}) as Row,adjustments:Array.isArray(row.adjustment_snapshot)?row.adjustment_snapshot as TimesheetAdjustment[]:[],calculationVersion:number(row,"calculation_version")};}
function mapSummary(row:Row):TimesheetSummary{const e=(row.employee_snapshot??{}) as Row;return{id:text(row,"id"),periodId:text(row,"period_id"),employeeId:text(row,"employee_id"),employeeCode:text(e,"code"),employeeName:text(e,"name"),departmentName:text(e,"departmentName"),positionName:text(e,"positionName"),employmentTypeName:text(e,"employmentTypeName"),scheduledWorkdays:number(row,"scheduled_workdays"),actualWorkdays:number(row,"actual_workdays"),workedMinutes:number(row,"worked_minutes"),lateDays:number(row,"late_days"),lateMinutes:number(row,"late_minutes"),earlyLeaveDays:number(row,"early_leave_days"),earlyLeaveMinutes:number(row,"early_leave_minutes"),annualLeaveDays:number(row,"annual_leave_days"),unpaidLeaveDays:number(row,"unpaid_leave_days"),absentDays:number(row,"absent_days"),businessTripDays:number(row,"business_trip_days"),holidayDays:number(row,"holiday_days"),missingCheckInDays:number(row,"missing_check_in_days"),missingCheckOutDays:number(row,"missing_check_out_days"),exceptionCount:number(row,"exception_count")};}

export async function listShifts(user:AuthenticatedUser){requireAny(user,["shift.view","shift.manage"]);const client=db();const [{data,error},{data:assignments,error:assignmentError}]=await Promise.all([client.from("shifts").select("*").order("code"),client.from("shift_assignments").select("*").order("effective_from",{ascending:false})]);if(error||assignmentError)throw new AppError("SERVER_ERROR","Không thể đọc cấu hình ca làm.");return{shifts:(data??[]).map(row=>mapShift(row as Row)),assignments:assignments??[]};}
export async function saveShift(user:AuthenticatedUser,input:ShiftInput){if(!can(user.permissions,"shift.manage"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const values={code:input.code,name:input.name,start_time:input.startTime,end_time:input.endTime,break_minutes:input.breakMinutes,late_grace_minutes:input.lateGraceMinutes,early_leave_grace_minutes:input.earlyLeaveGraceMinutes,check_in_earliest_minutes:input.checkInEarliestMinutes,check_in_latest_minutes:input.checkInLatestMinutes,check_out_earliest_minutes:input.checkOutEarliestMinutes,check_out_latest_minutes:input.checkOutLatestMinutes,cross_midnight:input.crossMidnight,active:input.active};const operation=input.id?client.from("shifts").update(values).eq("id",input.id):client.from("shifts").insert({...values,created_by:actor});const {data,error}=await operation.select("*").single();if(error||!data)throw new AppError(error?.code==="23505"?"DUPLICATE":"SERVER_ERROR","Không thể lưu ca làm.");await recordAuditLog({actorId:actor,action:"shift.saved",entityType:"shift",entityId:String(data.id),after:values});return mapShift(data as Row);}
export async function saveShiftAssignment(user:AuthenticatedUser,input:{shiftId:string;scopeType:string;scopeId?:string;effectiveFrom:string;effectiveTo?:string;weekdays:number[]}){if(!can(user.permissions,"shift.manage"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const {data,error}=await client.from("shift_assignments").insert({shift_id:input.shiftId,scope_type:input.scopeType,scope_id:input.scopeId??null,effective_from:input.effectiveFrom,effective_to:input.effectiveTo??null,weekdays:input.weekdays,created_by:actor}).select("*").single();if(error||!data)throw new AppError(error?.code==="23505"?"DUPLICATE":"SERVER_ERROR","Không thể gán ca làm.");return data;}
export async function listCalendar(user:AuthenticatedUser,from?:string,to?:string){requireAny(user,["shift.view","shift.manage"]);let query=db().from("work_calendar_days").select("*").order("calendar_date");if(from)query=query.gte("calendar_date",from);if(to)query=query.lte("calendar_date",to);const {data,error}=await query;if(error)throw new AppError("SERVER_ERROR","Không thể đọc lịch làm việc.");return(data??[]).map(row=>({id:String(row.id),date:String(row.calendar_date),name:String(row.name),dayType:row.day_type,scopeType:row.scope_type,scopeId:row.scope_id??undefined,isWorkingDay:Boolean(row.is_working_day),active:Boolean(row.active)}));}
export async function saveCalendarDay(user:AuthenticatedUser,input:CalendarInput){if(!can(user.permissions,"shift.manage"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const values={calendar_date:input.date,name:input.name,day_type:input.dayType,scope_type:input.scopeType,scope_id:input.scopeId??null,is_working_day:input.isWorkingDay,active:input.active};const operation=input.id?client.from("work_calendar_days").update(values).eq("id",input.id):client.from("work_calendar_days").insert({...values,created_by:actor});const {data,error}=await operation.select("*").single();if(error||!data)throw new AppError(error?.code==="23505"?"DUPLICATE":"SERVER_ERROR","Không thể lưu ngày lịch.");return data;}

export async function listPeriods(user:AuthenticatedUser){requireAny(user,["timesheet.view","timesheet.self.view","timesheet.view_all","timesheet.view_team"]);const {data,error}=await db().from("timesheet_periods").select("*").order("start_date",{ascending:false});if(error)throw new AppError("SERVER_ERROR","Không thể đọc kỳ công.");return(data??[]).map(row=>mapPeriod(row as Row));}
export async function createPeriod(user:AuthenticatedUser,input:{code:string;name:string;startDate:string;endDate:string}){if(!can(user.permissions,"timesheet.adjust")&&!can(user.permissions,"timesheet.lock"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const {data,error}=await client.from("timesheet_periods").insert({code:input.code,name:input.name,start_date:input.startDate,end_date:input.endDate,created_by:actor}).select("*").single();if(error||!data)throw new AppError(error?.code==="23505"?"DUPLICATE":"SERVER_ERROR","Không thể tạo kỳ công.");await recordAuditLog({actorId:actor,action:"timesheet.period_created",entityType:"timesheet_period",entityId:String(data.id)});return mapPeriod(data as Row);}
export async function getPeriod(user:AuthenticatedUser,id:string){requireAny(user,["timesheet.view","timesheet.self.view","timesheet.view_all","timesheet.view_team"]);const client=db();const scope=await visibleEmployeeIds(client,user);let summaryQuery=client.from("timesheet_period_summaries").select("*").eq("period_id",id).order("employee_id");let dailyQuery=client.from("daily_timesheets").select("*").eq("period_id",id).order("work_date");if(scope){summaryQuery=summaryQuery.in("employee_id",scope);dailyQuery=dailyQuery.in("employee_id",scope);}const [{data:period,error},{data:summaries},{data:daily}]=await Promise.all([client.from("timesheet_periods").select("*").eq("id",id).maybeSingle(),summaryQuery,dailyQuery]);if(error||!period)throw new AppError("NOT_FOUND","Không tìm thấy kỳ công.");return{period:mapPeriod(period as Row),summaries:(summaries??[]).map(row=>mapSummary(row as Row)),daily:(daily??[]).map(row=>mapDaily(row as Row))};}

function adjustment(row:Row):TimesheetAdjustment{return{id:text(row,"id"),periodId:text(row,"period_id"),employeeId:text(row,"employee_id"),workDate:text(row,"work_date"),adjustmentType:text(row,"adjustment_type") as TimesheetAdjustment["adjustmentType"],effectiveTime:optional(row,"effective_time"),correctedStatus:optional(row,"corrected_status") as TimesheetAdjustment["correctedStatus"],correctedWorkFraction:row.corrected_work_fraction==null?undefined:Number(row.corrected_work_fraction),hrNote:optional(row,"hr_note"),reason:text(row,"reason"),createdAt:text(row,"created_at"),before:(row.before_snapshot??{}) as Row,after:(row.after_snapshot??{}) as Row};}
const key=(employeeId:string,date:string)=>`${employeeId}:${date}`;

export async function listAdjustments(user:AuthenticatedUser,periodId:string,employeeId?:string,workDate?:string){
  requireAny(user,["timesheet.view","timesheet.self.view","timesheet.view_all","timesheet.view_team","timesheet.adjust"]);
  const client=db();
  const scope=await visibleEmployeeIds(client,user);
  let query=client.from("timesheet_adjustments").select("*").eq("period_id",periodId).order("created_at",{ascending:false});
  if(scope)query=query.in("employee_id",scope);
  if(employeeId)query=query.eq("employee_id",employeeId);
  if(workDate)query=query.eq("work_date",workDate);
  const {data,error}=await query;
  if(error)throw new AppError("SERVER_ERROR","Không thể đọc lịch sử điều chỉnh.");
  return(data??[]).map(row=>adjustment(row as Row));
}

export async function recomputePeriod(user:AuthenticatedUser,periodId:string){if(!can(user.permissions,"timesheet.adjust")&&!can(user.permissions,"timesheet.lock"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const {data:periodRow}=await client.from("timesheet_periods").select("*").eq("id",periodId).maybeSingle();if(!periodRow)throw new AppError("NOT_FOUND","Không tìm thấy kỳ công.");const period=mapPeriod(periodRow as Row);if(period.status==="locked")throw new AppError("CONFLICT","Kỳ công đã khóa.");const workDates=dates(period.startDate,period.endDate);
  const [employeesResult,departmentsResult,positionsResult,typesResult,shiftsResult,assignmentsResult,calendarResult,eventsResult,projectsResult,workerResult,leaveResult,adjustmentsResult]=await Promise.all([
    client.from("employees").select("id,employee_code,full_name,department_id,position_id,employment_type_id,join_date,termination_date,employment_status").lte("join_date",period.endDate).or(`termination_date.is.null,termination_date.gte.${period.startDate}`),
    client.from("departments").select("id,name"),client.from("positions").select("id,name"),client.from("employment_types").select("id,name"),client.from("shifts").select("*").eq("active",true),client.from("shift_assignments").select("*").eq("active",true).lte("effective_from",period.endDate).or(`effective_to.is.null,effective_to.gte.${period.startDate}`),client.from("work_calendar_days").select("*").eq("active",true).gte("calendar_date",period.startDate).lte("calendar_date",period.endDate),client.from("attendance_events").select("id,employee_id,event_type,attendance_date,effective_at,geofence_status,photo_status,sync_status,attendance_locations(name),attendance_photos(id)").gte("attendance_date",period.startDate).lte("attendance_date",period.endDate),client.from("project_assignments").select("employee_id,project_id,start_date,end_date,status").lte("start_date",period.endDate).or(`end_date.is.null,end_date.gte.${period.startDate}`),client.from("worker_attendance_entries").select("worker_id,status,day_exception,session_id,worker_attendance_sessions!inner(attendance_date,project_name_snapshot,worksite_name_snapshot,status)").gte("worker_attendance_sessions.attendance_date",period.startDate).lte("worker_attendance_sessions.attendance_date",period.endDate).in("worker_attendance_sessions.status",["submitted","locked","needs_review"]),client.from("leave_requests").select("id,request_number,employee_id,start_date,end_date,start_day_part,end_day_part,leave_types(code,name,deducts_balance)").eq("status","approved").lte("start_date",period.endDate).gte("end_date",period.startDate),client.from("timesheet_adjustments").select("*").eq("period_id",periodId).order("created_at")
  ]);
  const failed=[employeesResult,departmentsResult,positionsResult,typesResult,shiftsResult,assignmentsResult,calendarResult,eventsResult,projectsResult,workerResult,leaveResult,adjustmentsResult].find(result=>result.error);if(failed?.error)throw new AppError("SERVER_ERROR",`Không thể tổng hợp kỳ công: ${failed.error.message}`);
  const nameMap=(rows:unknown[]|null)=>new Map((rows??[]).map(value=>{const row=value as Row;return[String(row.id),text(row,"name")]}));const departments=nameMap(departmentsResult.data);const positions=nameMap(positionsResult.data);const employmentTypes=nameMap(typesResult.data);const shiftMap=new Map((shiftsResult.data??[]).map(value=>{const item=mapShift(value as Row);return[item.id,item]}));
  const shiftAssignments=(assignmentsResult.data??[]).map(value=>{const row=value as Row;return{scopeType:text(row,"scope_type") as "company"|"department"|"project"|"employee",scopeId:optional(row,"scope_id"),effectiveFrom:text(row,"effective_from"),effectiveTo:optional(row,"effective_to"),weekdays:Array.isArray(row.weekdays)?row.weekdays.map(Number):[],shift:shiftMap.get(text(row,"shift_id"))!}}).filter(item=>item.shift);
  const calendar=(calendarResult.data??[]).map(value=>{const row=value as Row;return{id:text(row,"id"),date:text(row,"calendar_date"),name:text(row,"name"),dayType:text(row,"day_type") as CalendarDay["dayType"],scopeType:text(row,"scope_type") as CalendarDay["scopeType"],scopeId:optional(row,"scope_id"),isWorkingDay:Boolean(row.is_working_day),active:Boolean(row.active)};});
  const events=new Map<string,Row[]>();for(const value of eventsResult.data??[]){const row=value as Row;events.set(key(text(row,"employee_id"),text(row,"attendance_date")),[...(events.get(key(text(row,"employee_id"),text(row,"attendance_date")))??[]),row]);}
  const projects=new Map<string,Row[]>();for(const value of projectsResult.data??[]){const row=value as Row;projects.set(text(row,"employee_id"),[...(projects.get(text(row,"employee_id"))??[]),row]);}
  const workers=new Map<string,Row>();for(const value of workerResult.data??[]){const row=value as Row;const session=row.worker_attendance_sessions as Row;workers.set(key(text(row,"worker_id"),text(session,"attendance_date")),row);}
  const leaves=new Map<string,Row>();for(const value of leaveResult.data??[]){const row=value as Row;for(const date of workDates)if(date>=text(row,"start_date")&&date<=text(row,"end_date"))leaves.set(key(text(row,"employee_id"),date),row);}
  const adjustments=new Map<string,TimesheetAdjustment[]>();for(const value of adjustmentsResult.data??[]){const item=adjustment(value as Row);adjustments.set(key(item.employeeId,item.workDate),[...(adjustments.get(key(item.employeeId,item.workDate))??[]),item]);}
  const computed=[];for(const value of employeesResult.data??[]){const employee=value as Row;const employeeId=text(employee,"id");for(const date of workDates){if(date<text(employee,"join_date")||optional(employee,"termination_date")&&date>text(employee,"termination_date"))continue;const projectIds=(projects.get(employeeId)??[]).filter(item=>text(item,"start_date")<=date&&(!optional(item,"end_date")||text(item,"end_date")>=date)&&text(item,"status")!=="cancelled").map(item=>text(item,"project_id"));const eventInputs=(events.get(key(employeeId,date))??[]).map(item=>{const photos=item.attendance_photos as Row[]|Row|undefined;const photo=Array.isArray(photos)?photos[0]:photos;const location=item.attendance_locations as Row|undefined;return{id:text(item,"id"),eventType:text(item,"event_type") as "check_in"|"check_out",effectiveAt:text(item,"effective_at"),geofenceStatus:text(item,"geofence_status"),photoStatus:text(item,"photo_status"),syncStatus:text(item,"sync_status"),locationName:location?optional(location,"name"):undefined,photoId:photo?optional(photo,"id"):undefined};});const worker=workers.get(key(employeeId,date));const session=worker?.worker_attendance_sessions as Row|undefined;const leave=leaves.get(key(employeeId,date));const leaveType=leave?.leave_types as Row|undefined;let fraction=1;if(leave&&(text(leave,"start_date")===date&&text(leave,"start_day_part")!=="full_day"||text(leave,"end_date")===date&&text(leave,"end_day_part")!=="full_day"))fraction=.5;computed.push(computeDailyTimesheet({periodId,employee:{id:employeeId,code:text(employee,"employee_code"),name:text(employee,"full_name"),departmentName:departments.get(text(employee,"department_id"))??"",positionName:positions.get(text(employee,"position_id"))??"",employmentTypeName:employmentTypes.get(text(employee,"employment_type_id"))??""},date,shift:resolveShift({assignments:shiftAssignments,date,employeeId,departmentId:text(employee,"department_id"),projectIds}),calendarDay:resolveCalendarDay(calendar,{date,employeeId,departmentId:text(employee,"department_id"),projectIds}),events:eventInputs,worker:worker&&session?{status:text(worker,"status") as "present"|"absent"|"leave"|"late"|"transferred"|"unconfirmed",dayException:optional(worker,"day_exception"),projectName:optional(session,"project_name_snapshot"),worksiteName:optional(session,"worksite_name_snapshot"),sessionId:optional(worker,"session_id")}:undefined,leave:leave&&leaveType?{requestId:text(leave,"id"),requestNumber:text(leave,"request_number"),typeCode:text(leaveType,"code"),typeName:text(leaveType,"name"),deductsBalance:Boolean(leaveType.deducts_balance),fraction}:undefined,adjustments:adjustments.get(key(employeeId,date))??[]}));}}
  const dailyRows=computed.map(item=>({period_id:item.periodId,employee_id:item.employeeId,work_date:item.workDate,employee_snapshot:{code:item.employeeCode,name:item.employeeName,departmentName:item.departmentName,positionName:item.positionName,employmentTypeName:item.employmentTypeName},shift_id:item.shiftId??null,shift_snapshot:item.shiftId?{name:item.shiftName,startTime:item.shiftStart,endTime:item.shiftEnd}:null,source_codes:item.sources,raw_source_snapshot:item.rawSource,effective_check_in:item.effectiveCheckIn??null,effective_check_out:item.effectiveCheckOut??null,work_minutes:item.workMinutes,work_fraction:item.workFraction,leave_fraction:item.leaveFraction,late_minutes:item.lateMinutes,early_leave_minutes:item.earlyLeaveMinutes,leave_type_code:item.leaveTypeCode??null,leave_type_name:item.leaveTypeName??null,status:item.status,hr_note:item.hrNote??null,exception_count:item.exceptionCount,adjustment_snapshot:item.adjustments,calculation_version:item.calculationVersion,computed_at:new Date().toISOString()}));const {data:upserted,error:upsertError}=await client.from("daily_timesheets").upsert(dailyRows,{onConflict:"period_id,employee_id,work_date"}).select("id,employee_id,work_date");if(upsertError)throw new AppError("SERVER_ERROR",`Không thể lưu bảng công ngày: ${upsertError.message}`);const dailyIds=new Map((upserted??[]).map(item=>[key(String(item.employee_id),String(item.work_date)),String(item.id)]));await client.from("timesheet_exceptions").delete().eq("period_id",periodId).eq("status","open");const exceptionRows=computed.flatMap(item=>item.exceptions.map(exception=>({period_id:periodId,daily_timesheet_id:dailyIds.get(key(item.employeeId,item.workDate)),employee_id:item.employeeId,work_date:item.workDate,exception_type:exception.type,severity:exception.severity,details:exception.details}))).filter(item=>item.daily_timesheet_id);if(exceptionRows.length){const {error}=await client.from("timesheet_exceptions").upsert(exceptionRows,{onConflict:"daily_timesheet_id,exception_type"});if(error)throw new AppError("SERVER_ERROR",`Không thể lưu ngoại lệ: ${error.message}`);}
  const groups=new Map<string,typeof computed>();for(const item of computed)groups.set(item.employeeId,[...(groups.get(item.employeeId)??[]),item]);const summaries=[...groups.values()].map(items=>{const first=items[0];return{period_id:periodId,employee_id:first.employeeId,employee_snapshot:{code:first.employeeCode,name:first.employeeName,departmentName:first.departmentName,positionName:first.positionName,employmentTypeName:first.employmentTypeName},scheduled_workdays:items.filter(item=>item.status!=="holiday"&&item.status!=="rest_day").length,actual_workdays:items.reduce((sum,item)=>sum+item.workFraction,0),worked_minutes:items.reduce((sum,item)=>sum+item.workMinutes,0),late_days:items.filter(item=>item.lateMinutes>0).length,late_minutes:items.reduce((sum,item)=>sum+item.lateMinutes,0),early_leave_days:items.filter(item=>item.earlyLeaveMinutes>0).length,early_leave_minutes:items.reduce((sum,item)=>sum+item.earlyLeaveMinutes,0),annual_leave_days:items.filter(item=>item.status==="annual_leave").reduce((sum,item)=>sum+item.leaveFraction,0),unpaid_leave_days:items.filter(item=>item.status==="unpaid_leave").reduce((sum,item)=>sum+item.leaveFraction,0),absent_days:items.filter(item=>item.status==="absent").length,business_trip_days:items.filter(item=>item.status==="business_trip").length,holiday_days:items.filter(item=>item.status==="holiday").length,missing_check_in_days:items.filter(item=>item.status==="missing_check_in").length,missing_check_out_days:items.filter(item=>item.status==="missing_check_out").length,exception_count:items.reduce((sum,item)=>sum+item.exceptionCount,0),computed_at:new Date().toISOString()};});if(summaries.length){const {error}=await client.from("timesheet_period_summaries").upsert(summaries,{onConflict:"period_id,employee_id"});if(error)throw new AppError("SERVER_ERROR",`Không thể lưu tổng hợp: ${error.message}`);}if(period.status==="open")await client.from("timesheet_periods").update({status:"reviewing"}).eq("id",periodId);await recordAuditLog({actorId:actor,action:"timesheet.recomputed",entityType:"timesheet_period",entityId:periodId,metadata:{dailyRows:computed.length,exceptions:exceptionRows.length}});return{dailyRows:computed.length,exceptions:exceptionRows.length,employees:groups.size};
}

export async function addAdjustment(user:AuthenticatedUser,periodId:string,input:{employeeId:string;workDate:string;adjustmentType:string;effectiveTime?:string;correctedStatus?:string;correctedWorkFraction?:number;hrNote?:string;reason:string;rowVersion:number}){if(!can(user.permissions,"timesheet.adjust"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const {data:period}=await client.from("timesheet_periods").select("status,row_version").eq("id",periodId).maybeSingle();if(!period)throw new AppError("NOT_FOUND");if(period.status==="locked"||Number(period.row_version)!==input.rowVersion)throw new AppError("CONFLICT","Kỳ công đã thay đổi hoặc đang khóa.");const {data:before}=await client.from("daily_timesheets").select("*").eq("period_id",periodId).eq("employee_id",input.employeeId).eq("work_date",input.workDate).maybeSingle();const {data,error}=await client.from("timesheet_adjustments").insert({period_id:periodId,employee_id:input.employeeId,work_date:input.workDate,adjustment_type:input.adjustmentType,effective_time:input.effectiveTime??null,corrected_status:input.correctedStatus??null,corrected_work_fraction:input.correctedWorkFraction??null,hr_note:input.hrNote??null,reason:input.reason,before_snapshot:before??{},after_snapshot:{...input,rowVersion:undefined},created_by:actor}).select("*").single();if(error||!data)throw new AppError("SERVER_ERROR","Không thể lưu điều chỉnh.");await recordAuditLog({actorId:actor,action:"timesheet.adjustment_created",entityType:"timesheet_adjustment",entityId:String(data.id),before:before??{},after:input});await recomputePeriod(user,periodId);return adjustment(data as Row);}
export async function listExceptions(user:AuthenticatedUser,periodId?:string){requireAny(user,["timesheet.adjust","timesheet.view_all","timesheet.view_team"]);const client=db();const scope=await visibleEmployeeIds(client,user);let query=client.from("timesheet_exceptions").select("*,employees(employee_code,full_name)").order("work_date",{ascending:false});if(periodId)query=query.eq("period_id",periodId);if(scope)query=query.in("employee_id",scope);const {data,error}=await query;if(error)throw new AppError("SERVER_ERROR","Không thể đọc ngoại lệ.");return(data??[]).map(value=>{const row=value as Row;const employee=row.employees as Row;return{id:text(row,"id"),periodId:text(row,"period_id"),dailyTimesheetId:text(row,"daily_timesheet_id"),employeeId:text(row,"employee_id"),employeeCode:text(employee,"employee_code"),employeeName:text(employee,"full_name"),workDate:text(row,"work_date"),type:text(row,"exception_type"),severity:text(row,"severity"),status:text(row,"status"),details:row.details??{},resolutionNote:optional(row,"resolution_note")} as TimesheetException;});}
export async function resolveException(user:AuthenticatedUser,id:string,input:{status:"resolved"|"ignored";note:string}){if(!can(user.permissions,"timesheet.adjust"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const {data,error}=await client.from("timesheet_exceptions").update({status:input.status,resolution_note:input.note,resolved_by:actor,resolved_at:new Date().toISOString()}).eq("id",id).eq("status","open").select("id").maybeSingle();if(error||!data)throw new AppError("CONFLICT","Ngoại lệ đã được xử lý.");await recordAuditLog({actorId:actor,action:"timesheet.exception_resolved",entityType:"timesheet_exception",entityId:id,after:input});return{id};}
export async function lockPeriod(user:AuthenticatedUser,id:string,rowVersion:number){if(!can(user.permissions,"timesheet.lock"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const {data,error}=await client.rpc("lock_timesheet_period",{p_period_id:id,p_actor_id:actor,p_expected_row_version:rowVersion});if(error){if(error.message.includes("HIGH_EXCEPTIONS")||error.message.includes("VERSION_CONFLICT"))throw new AppError("CONFLICT",error.message.includes("HIGH")?"Còn ngoại lệ nghiêm trọng chưa xử lý.":"Kỳ công đã thay đổi.");throw new AppError("SERVER_ERROR","Không thể khóa kỳ công.");}await recordAuditLog({actorId:actor,action:"timesheet.period_locked",entityType:"timesheet_period",entityId:id,metadata:{version:data}});return{version:Number(data)};}
export async function unlockPeriod(user:AuthenticatedUser,id:string,rowVersion:number,reason:string){if(!can(user.permissions,"timesheet.unlock"))throw new AppError("PERMISSION_DENIED");const client=db();const actor=await actorId(client,user);const {data,error}=await client.rpc("unlock_timesheet_period",{p_period_id:id,p_actor_id:actor,p_expected_row_version:rowVersion,p_reason:reason});if(error)throw new AppError(error.message.includes("VERSION_CONFLICT")?"CONFLICT":"SERVER_ERROR","Không thể mở khóa kỳ công.");await recordAuditLog({actorId:actor,action:"timesheet.period_unlocked",entityType:"timesheet_period",entityId:id,metadata:{version:data,reason}});return{version:Number(data)};}
