import { describe, expect, it } from "vitest";
import { computeDailyTimesheet, resolveCalendarDay, resolveShift, scheduledMinutes } from "./timesheetRules";
import type { Shift } from "../types/timesheetTypes";

const shift: Shift = { id:"1", code:"OFFICE", name:"Hành chính", startTime:"08:00", endTime:"17:00", breakMinutes:60, lateGraceMinutes:5, earlyLeaveGraceMinutes:5, checkInEarliestMinutes:120, checkInLatestMinutes:240, checkOutEarliestMinutes:0, checkOutLatestMinutes:360, crossMidnight:false, active:true };
const base = { periodId:"p", employee:{id:"e",code:"NV01",name:"An",departmentName:"HC",positionName:"NV",employmentTypeName:"Chính thức"}, date:"2026-09-10", shift, adjustments:[] };

describe("timesheet rules", () => {
  it("tính ca thường và ca qua đêm", () => { expect(scheduledMinutes(shift)).toBe(480); expect(scheduledMinutes({...shift,startTime:"22:00",endTime:"06:00",crossMidnight:true})).toBe(420); });
  it("áp dụng độ trễ cho phép", () => { const result=computeDailyTimesheet({...base,events:[{id:"in",eventType:"check_in",effectiveAt:"2026-09-10T01:05:00Z",geofenceStatus:"inside",photoStatus:"uploaded",syncStatus:"synced"},{id:"out",eventType:"check_out",effectiveAt:"2026-09-10T10:00:00Z",geofenceStatus:"inside",photoStatus:"uploaded",syncStatus:"synced"}]});expect(result.status).toBe("full_work");expect(result.lateMinutes).toBe(0);expect(result.workMinutes).toBe(475); });
  it("giữ nhiều lượt vào/ra và phát hiện thiếu lượt ra", () => { const result=computeDailyTimesheet({...base,events:[{id:"1",eventType:"check_in",effectiveAt:"2026-09-10T01:00:00Z",geofenceStatus:"inside",photoStatus:"uploaded",syncStatus:"synced"},{id:"2",eventType:"check_out",effectiveAt:"2026-09-10T05:00:00Z",geofenceStatus:"inside",photoStatus:"uploaded",syncStatus:"synced"},{id:"3",eventType:"check_in",effectiveAt:"2026-09-10T06:00:00Z",geofenceStatus:"inside",photoStatus:"uploaded",syncStatus:"synced"}]});expect(result.workMinutes).toBe(240);expect(result.status).toBe("missing_check_out");expect(result.rawSource.events).toHaveLength(3); });
  it("đánh dấu xung đột chấm công với đơn nghỉ", () => { const result=computeDailyTimesheet({...base,events:[{id:"1",eventType:"check_in",effectiveAt:"2026-09-10T01:00:00Z",geofenceStatus:"inside",photoStatus:"uploaded",syncStatus:"synced"}],leave:{requestId:"l",requestNumber:"NP1",typeCode:"AL",typeName:"Phép năm",deductsBalance:true,fraction:1}});expect(result.status).toBe("needs_review");expect(result.exceptions.some(item=>item.type==="attendance_leave_conflict")).toBe(true); });
  it("áp dụng dữ liệu đội công nhân và điều chỉnh HR", () => { const result=computeDailyTimesheet({...base,events:[],worker:{status:"present",dayException:"half_day"},adjustments:[{id:"a",periodId:"p",employeeId:"e",workDate:base.date,adjustmentType:"mark_business_trip",reason:"Công tác",createdAt:"2026-09-10T00:00:00Z",before:{},after:{}}]});expect(result.status).toBe("business_trip");expect(result.workFraction).toBe(.5);expect(result.sources).toContain("MANUAL_ADJUSTMENT"); });
  it("ưu tiên phạm vi nhân viên và lịch riêng", () => { const assignments=[{scopeType:"company" as const,effectiveFrom:"2020-01-01",weekdays:[4],shift},{scopeType:"employee" as const,scopeId:"e",effectiveFrom:"2020-01-01",weekdays:[4],shift:{...shift,id:"2",name:"Riêng"}}];expect(resolveShift({assignments,date:base.date,employeeId:"e",departmentId:"d",projectIds:[]})?.name).toBe("Riêng"); const days=[{id:"1",date:base.date,name:"Lễ",dayType:"holiday" as const,scopeType:"company" as const,isWorkingDay:false,active:true},{id:"2",date:base.date,name:"Đi làm",dayType:"makeup_workday" as const,scopeType:"employee" as const,scopeId:"e",isWorkingDay:true,active:true}];expect(resolveCalendarDay(days,{date:base.date,employeeId:"e",departmentId:"d",projectIds:[]})?.isWorkingDay).toBe(true); });
  it("dùng đúng phiên bản ca theo ngày hiệu lực", () => { const assignments=[{scopeType:"company" as const,effectiveFrom:"2020-01-01",weekdays:[4],shift:{...shift,name:"Hiện tại"},versions:[{effectiveFrom:"2020-01-01",effectiveTo:"2026-09-10",shift:{...shift,name:"Ca cũ",startTime:"07:00"}},{effectiveFrom:"2026-09-11",shift:{...shift,name:"Ca mới",startTime:"08:30"}}]}];expect(resolveShift({assignments,date:"2026-09-10",employeeId:"e",departmentId:"d",projectIds:[]})?.name).toBe("Ca cũ");expect(resolveShift({assignments,date:"2026-09-17",employeeId:"e",departmentId:"d",projectIds:[]})?.name).toBe("Ca mới"); });
});
