import "server-only";
import type {AccountRolesPatchInput,AccountStatusPatchInput,CreateEmployeeInput,PatchEmployeeInput,ProvisionAccountInput,SensitiveProfilePatchInput} from "@/features/employees/schemas/employeeSchemas";
import {normalizePhone} from "@/features/employees/services/employeeService";import {AppError} from "@/lib/api/errors";import {getSupabaseServiceClient} from "@/lib/supabase/server";
function db(){const client=getSupabaseServiceClient();if(!client)throw new AppError("SERVER_ERROR","Supabase chưa được cấu hình.");return client;}
function optional(value:string|undefined){return value?.trim()||null;}
function databaseError(error:{code?:string;message?:string}|null,message="Không thể lưu dữ liệu."){if(error?.code==="23505")return new AppError("CONFLICT","Mã/email/số định danh đã tồn tại.");if(error?.code==="23503")return new AppError("VALIDATION_ERROR","Dữ liệu tham chiếu không tồn tại.");return new AppError("SERVER_ERROR",message);}

export async function createEmployee(input:CreateEmployeeInput,actorId:string){const client=db(),id=crypto.randomUUID();const {data,error}=await client.from("employees").insert({id,employee_code:input.employeeCode.trim(),full_name:input.fullName.trim(),display_name:optional(input.displayName)||input.fullName.trim(),personal_phone:input.personalPhone.trim(),normalized_phone:normalizePhone(input.personalPhone),personal_email:optional(input.personalEmail),company_email:optional(input.companyEmail),current_address:optional(input.currentAddress),province:optional(input.province),country:"Việt Nam",department_id:input.departmentId,position_id:input.positionId,employment_type_id:input.employmentTypeId,manager_employee_id:input.managerEmployeeId||null,contractor_name:optional(input.contractorName),join_date:input.joinDate,probation_start_date:input.probationStartDate||null,official_date:input.officialDate||null,employment_status:input.employmentStatus,profile_status:"pending_hr_completion",profile_completeness:0,note:optional(input.note),created_by:actorId}).select("id").single();if(error||!data)throw databaseError(error);await client.from("employee_history_events").insert({employee_id:id,event_type:"joined",event_date:input.joinDate,actor_account_id:actorId,after_data:{employeeCode:input.employeeCode,employmentStatus:input.employmentStatus}});return id;}

export async function patchEmployee(id:string,input:PatchEmployeeInput,actorId:string){const client=db();const{data:current}=await client.from("employees").select("*").eq("id",id).maybeSingle();if(!current)throw new AppError("NOT_FOUND","Không tìm thấy hồ sơ nhân sự.");const payload:Record<string,unknown>={};const assign=(key:string,value:unknown)=>{if(value!==undefined)payload[key]=typeof value==="string"?optional(value):value;};assign("employee_code",input.employeeCode);assign("full_name",input.fullName);assign("display_name",input.displayName);assign("personal_phone",input.personalPhone);if(input.personalPhone)payload.normalized_phone=normalizePhone(input.personalPhone);assign("personal_email",input.personalEmail);assign("company_email",input.companyEmail);assign("department_id",input.departmentId);assign("position_id",input.positionId);assign("employment_type_id",input.employmentTypeId);assign("manager_employee_id",input.managerEmployeeId);assign("join_date",input.joinDate);assign("probation_start_date",input.probationStartDate);assign("official_date",input.officialDate);assign("employment_status",input.employmentStatus);assign("current_address",input.currentAddress);assign("province",input.province);assign("contractor_name",input.contractorName);assign("note",input.note);assign("termination_date",input.terminationDate);assign("termination_reason",input.terminationReason);if(input.employmentStatus==="terminated")payload.profile_status="archived";
  const expected=input.rowVersion||Number(current.row_version);const{data,error}=await client.from("employees").update(payload).eq("id",id).eq("row_version",expected).select("row_version").maybeSingle();if(error)throw databaseError(error);if(!data)throw new AppError("CONFLICT","Hồ sơ vừa được người khác cập nhật.");if(input.employmentStatus==="terminated"){const{data:accounts}=await client.from("app_accounts").select("id").eq("employee_id",id);for(const account of accounts||[])await client.rpc("set_app_account_status",{p_account_id:account.id,p_status:"disabled",p_actor_id:actorId,p_reason:input.reason||input.terminationReason||"Offboarding"});}
  await client.from("employee_history_events").insert({employee_id:id,event_type:input.employmentStatus==="terminated"?"terminated":"profile_updated",event_date:(input.terminationDate||new Date().toISOString().slice(0,10)),actor_account_id:actorId,before_data:{rowVersion:expected},after_data:{rowVersion:data.row_version,employmentStatus:input.employmentStatus},reason:input.reason||input.terminationReason||null});return Number(data.row_version);}

export async function updateSensitiveProfile(id:string,input:SensitiveProfilePatchInput,actorId:string){const client=db();const payload={employee_id:id,national_id_number:optional(input.nationalIdNumber),national_id_issued_date:input.nationalIdIssuedDate||null,national_id_issued_place:optional(input.nationalIdIssuedPlace),national_id_expiry_date:input.nationalIdExpiryDate||null,bank_name:optional(input.bankName),bank_account_number:optional(input.bankAccountNumber),bank_account_holder:optional(input.bankAccountHolder),bank_branch:optional(input.bankBranch),personal_tax_code:optional(input.personalTaxCode),social_insurance_code:optional(input.socialInsuranceCode),updated_by:actorId,updated_at:new Date().toISOString()};const{data,error}=await client.from("employee_sensitive_profiles").upsert(payload,{onConflict:"employee_id"}).select("updated_at").single();if(error||!data)throw databaseError(error);await client.from("employee_history_events").insert({employee_id:id,event_type:"sensitive_updated",event_date:new Date().toISOString().slice(0,10),actor_account_id:actorId,after_data:{fields:Object.keys(input).filter(key=>key!=="reason")},reason:input.reason||null});return String(data.updated_at);}

export async function archiveEmployee(id:string,actorId:string,reason:string){const client=db();const{data,error}=await client.from("employees").update({profile_status:"archived"}).eq("id",id).neq("profile_status","archived").select("id").maybeSingle();if(error)throw databaseError(error);if(!data)throw new AppError("NOT_FOUND","Không tìm thấy hồ sơ hoặc hồ sơ đã lưu trữ.");await client.from("employee_history_events").insert({employee_id:id,event_type:"archived",event_date:new Date().toISOString().slice(0,10),actor_account_id:actorId,after_data:{profileStatus:"archived"},reason});return id;}

export async function provisionAccount(employeeId:string,input:ProvisionAccountInput,actorId:string){if(!input.loginEmail)throw new AppError("VALIDATION_ERROR","Email đăng nhập là bắt buộc khi dùng Supabase Auth.");const client=db();const{data:employee}=await client.from("employees").select("id,full_name").eq("id",employeeId).maybeSingle();if(!employee)throw new AppError("NOT_FOUND","Không tìm thấy nhân sự.");const{data:existing}=await client.from("app_accounts").select("id").eq("employee_id",employeeId).maybeSingle();if(existing)throw new AppError("CONFLICT","Nhân sự đã có tài khoản.");const{data:roles}=await client.from("roles").select("id").in("id",input.roleIds);if((roles||[]).length!==new Set(input.roleIds).size)throw new AppError("VALIDATION_ERROR","Vai trò không tồn tại.");const invited=await client.auth.admin.inviteUserByEmail(input.loginEmail,{data:{display_name:employee.full_name}});if(invited.error||!invited.data.user)throw new AppError("SERVER_ERROR","Không thể gửi lời mời tài khoản.");const{data:account,error}=await client.from("app_accounts").insert({auth_user_id:invited.data.user.id,employee_id:employeeId,display_name:employee.full_name,primary_email:input.loginEmail.toLowerCase(),phone:input.loginPhone||null,status:"invited"}).select("id").single();if(error||!account){await client.auth.admin.deleteUser(invited.data.user.id);throw databaseError(error);}
  const{error:roleError}=await client.from("account_roles").insert(input.roleIds.map(roleId=>({account_id:account.id,role_id:roleId,assigned_by:actorId})));if(roleError){await client.from("app_accounts").delete().eq("id",account.id);await client.auth.admin.deleteUser(invited.data.user.id);throw databaseError(roleError);}await client.from("employee_history_events").insert({employee_id:employeeId,event_type:"account_provisioned",event_date:new Date().toISOString().slice(0,10),actor_account_id:actorId,after_data:{accountId:account.id,status:"invited",roleIds:input.roleIds}});return String(account.id);}

export async function setAccountStatus(accountId:string,input:AccountStatusPatchInput,actorId:string){const client=db();const{data,error}=await client.rpc("set_app_account_status",{p_account_id:accountId,p_status:input.status,p_actor_id:actorId,p_reason:input.reason||null});if(error)throw new AppError(error.message.includes("LAST_ACTIVE_ADMIN")?"CONFLICT":"SERVER_ERROR",error.message.includes("LAST_ACTIVE_ADMIN")?"Không thể vô hiệu hóa admin hoạt động cuối cùng.":"Không thể cập nhật tài khoản.");return data;}
export async function replaceAccountRoles(accountId:string,input:AccountRolesPatchInput,actorId:string){const{error}=await db().rpc("replace_app_account_roles",{p_account_id:accountId,p_role_ids:[...new Set(input.roleIds)],p_actor_id:actorId});if(error)throw new AppError(error.message.includes("LAST_ACTIVE_ADMIN")?"CONFLICT":"SERVER_ERROR",error.message.includes("LAST_ACTIVE_ADMIN")?"Không thể bỏ vai trò admin cuối cùng.":"Không thể cập nhật vai trò.");}
