import "server-only";
import { AppError } from "@/lib/api/errors";
import { can, type AuthenticatedUser } from "@/lib/auth/permissions";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { humanizeAuditAction, sanitizeAuditValue } from "@/features/shared-platforms/rules";

type Row=Record<string,unknown>;
function db(){const client=getSupabaseServiceClient();if(!client)throw new AppError("SERVER_ERROR","Supabase chưa được cấu hình.");return client;}
function mapEntry(row:Row){const actor=(Array.isArray(row.app_accounts)?row.app_accounts[0]:row.app_accounts) as Row|undefined;return{id:String(row.id),actorName:typeof actor?.display_name==="string"?actor.display_name:"Hệ thống",actorAccountId:row.actor_account_id??null,action:String(row.action),actionLabel:humanizeAuditAction(String(row.action)),module:String(row.module??String(row.action).split(".")[0]),entityType:String(row.entity_type),entityId:String(row.entity_id),entityReference:row.entity_reference??null,happenedAt:String(row.happened_at),beforeData:sanitizeAuditValue(row.before_data),afterData:sanitizeAuditValue(row.after_data),reason:row.reason??null,source:row.source??"web",correlationId:row.correlation_id??null,severity:row.severity??"normal",metadata:sanitizeAuditValue(row.metadata)};}
export async function listAuditLogs(user:AuthenticatedUser,filters:{q?:string;module?:string;action?:string;from?:string;to?:string;severity?:string;page?:number}={}){if(!can(user.permissions,"audit.view"))throw new AppError("PERMISSION_DENIED");const page=Math.max(filters.page??1,1),size=50;let query=db().from("audit_logs").select("*,app_accounts!audit_logs_actor_account_id_fkey(display_name)",{count:"exact"}).order("happened_at",{ascending:false}).range((page-1)*size,page*size-1);if(filters.module)query=query.eq("module",filters.module);if(filters.action)query=query.ilike("action",`${filters.action}%`);if(filters.from)query=query.gte("happened_at",`${filters.from}T00:00:00+07:00`);if(filters.to)query=query.lte("happened_at",`${filters.to}T23:59:59+07:00`);if(filters.severity)query=query.eq("severity",filters.severity);if(!can(user.permissions,"audit.view_sensitive"))query=query.neq("severity","sensitive");if(filters.q){const safe=filters.q.replace(/[,%()]/g,"");query=query.or(`entity_id.ilike.%${safe}%,entity_reference.ilike.%${safe}%,action.ilike.%${safe}%`);}const{data,error,count}=await query;if(error)throw new AppError("SERVER_ERROR","Không thể đọc audit log.");return{entries:(data??[]).map(row=>mapEntry(row as Row)),page,pageCount:Math.max(1,Math.ceil((count??0)/size)),total:count??0};}
export async function getAuditLog(user:AuthenticatedUser,id:string){if(!can(user.permissions,"audit.view"))throw new AppError("PERMISSION_DENIED");let query=db().from("audit_logs").select("*,app_accounts!audit_logs_actor_account_id_fkey(display_name)").eq("id",id);if(!can(user.permissions,"audit.view_sensitive"))query=query.neq("severity","sensitive");const{data,error}=await query.maybeSingle();if(error||!data)throw new AppError("NOT_FOUND","Không tìm thấy sự kiện.");return mapEntry(data as Row);}

