import "server-only";
import { AppError } from "@/lib/api/errors";
import { can, type AuthenticatedUser, type Permission } from "@/lib/auth/permissions";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import type { DocumentRecord } from "@/features/shared-platforms/types";
import { resolvePlatformIdentity } from "./platformIdentity";
import { recordAuditLog } from "@/services/audit/auditLog";
import { publishNotificationEvent } from "./notificationRepository";

type Row=Record<string,unknown>;const documentSelect="*,document_types(name),file_assets!documents_current_file_id_fkey(mime_type,byte_size,metadata,bucket,object_path)";
const allowedMime=new Set(["image/jpeg","image/png","image/webp","application/pdf","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.openxmlformats-officedocument.wordprocessingml.document"]);
function db(){const client=getSupabaseServiceClient();if(!client)throw new AppError("SERVER_ERROR","Supabase chưa được cấu hình.");return client;}
function nested(row:Row,key:string):Row{const v=row[key];return(Array.isArray(v)?v[0]:v) as Row??{};}
function txt(row:Row,key:string,fallback=""){const v=row[key];return typeof v==="string"&&v?v:fallback;}
function mapDocument(row:Row):DocumentRecord{const file=nested(row,"file_assets"),metadata=nested(file,"metadata"),type=nested(row,"document_types");return{id:String(row.id),title:String(row.title),documentTypeId:String(row.document_type_id),documentTypeName:txt(type,"name","Khác"),fileId:String(row.current_file_id),fileName:txt(metadata,"originalName",txt(metadata,"fileName",String(row.title))),mimeType:txt(file,"mime_type"),byteSize:Number(file.byte_size??0),ownerEntityType:String(row.owner_entity_type),ownerEntityId:String(row.owner_entity_id),ownerReference:txt(row,"owner_reference")||undefined,visibilityScope:row.visibility_scope as DocumentRecord["visibilityScope"],status:row.status as DocumentRecord["status"],currentVersion:Number(row.current_version),expiryDate:txt(row,"expiry_date")||undefined,createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}

async function canAccess(user:AuthenticatedUser,document:DocumentRecord){if(!can(user.permissions,"document.view"))return false;if(document.visibilityScope==="company_wide")return true;const client=db(),actor=await resolvePlatformIdentity(client,user);if(document.ownerEntityType==="project_update"){
    if(can(user.permissions,"project_update.view_all")||can(user.permissions,"project_monitoring.view_all"))return true;const{data:update}=await client.from("project_updates").select("project_id").eq("id",document.ownerEntityId).maybeSingle();if(!update||!actor.employeeId)return false;const{data:assignment}=await client.from("project_assignments").select("id").eq("project_id",update.project_id).eq("employee_id",actor.employeeId).eq("status","active").limit(1).maybeSingle();return Boolean(assignment);
  }if(document.ownerEntityType==="shipment_document"){if(!can(user.permissions,"shipment_document.view"))return false;if(can(user.permissions,"import_export.view_all"))return true;const{data:shipment}=await client.from("shipments").select("assigned_account_id,created_by").eq("id",document.ownerEntityId).maybeSingle();return shipment?.assigned_account_id===actor.accountId||shipment?.created_by===actor.accountId;
  }if(document.ownerEntityType==="inventory_document"){const{data:item}=await client.from("inventory_documents").select("type,source_warehouse_id,target_warehouse_id,reverses_document_id").eq("id",document.ownerEntityId).maybeSingle();if(!item)return false;let type=item.type;if(type==="reversal"&&item.reverses_document_id){const{data:original}=await client.from("inventory_documents").select("type").eq("id",item.reverses_document_id).maybeSingle();type=original?.type??"receipt";}if(!can(user.permissions,`warehouse.${type}.view` as Permission))return false;if(can(user.permissions,"warehouse.view_all"))return true;const ids=[item.source_warehouse_id,item.target_warehouse_id].filter(Boolean);const{data:scope}=ids.length?await client.from("warehouse_user_scopes").select("warehouse_id").eq("account_id",actor.accountId).eq("can_view",true).in("warehouse_id",ids):{data:[]};return Boolean(scope?.length);
  }if(["employee","employee_document"].includes(document.ownerEntityType))return can(user.permissions,"employee.view")&&(document.ownerEntityId===actor.employeeId||can(user.permissions,"employee.view_sensitive"));if(document.ownerEntityType==="leave_request"){const{data:request}=await client.from("leave_requests").select("employee_id,created_by").eq("id",document.ownerEntityId).maybeSingle();return request?.employee_id===actor.employeeId||request?.created_by===actor.accountId||can(user.permissions,"leave.view_all");}return can(user.permissions,"document.company_manage");}

export async function listDocumentTypes(activeOnly=true){const{data,error}=await db().from("document_types").select("id,code,name,active,sort_order").order("sort_order");if(error)throw new AppError("SERVER_ERROR");return(data??[]).filter(row=>!activeOnly||row.active).map(row=>({id:row.id,code:row.code,name:row.name,active:row.active}));}
export async function listDocuments(user:AuthenticatedUser,options:{q?:string;typeId?:string;module?:string;view?:"all"|"recent"|"shared"}={}){if(!can(user.permissions,"document.view"))throw new AppError("PERMISSION_DENIED");let query=db().from("documents").select(documentSelect).neq("status","deleted_pending_retention").order("updated_at",{ascending:false}).limit(100);if(options.q)query=query.ilike("title",`%${options.q.replaceAll("%","")}%`);if(options.typeId)query=query.eq("document_type_id",options.typeId);if(options.module)query=query.eq("owner_entity_type",options.module);if(options.view==="recent")query=query.gte("updated_at",new Date(Date.now()-30*86400000).toISOString());if(options.view==="shared")query=query.eq("visibility_scope","company_wide");const{data,error}=await query;if(error)throw new AppError("SERVER_ERROR","Không thể đọc tài liệu.");const mapped=(data??[]).map(row=>mapDocument(row as Row));const access=await Promise.all(mapped.map(item=>canAccess(user,item)));return mapped.filter((_item,index)=>access[index]);}
export async function getDocument(user:AuthenticatedUser,id:string){const{data,error}=await db().from("documents").select(documentSelect).eq("id",id).maybeSingle();if(error||!data)throw new AppError("NOT_FOUND","Không tìm thấy tài liệu.");const item=mapDocument(data as Row);if(!await canAccess(user,item))throw new AppError("PERMISSION_DENIED");return item;}
export async function getDocumentVersions(user:AuthenticatedUser,id:string){await getDocument(user,id);const{data,error}=await db().from("document_versions").select("id,version_number,file_id,uploaded_at,change_note,app_accounts(display_name)").eq("document_id",id).order("version_number",{ascending:false});if(error)throw new AppError("SERVER_ERROR");return data??[];}
export async function getDocumentAsset(user:AuthenticatedUser,id:string){const item=await getDocument(user,id);const{data,error}=await db().from("file_assets").select("bucket,object_path").eq("id",item.fileId).maybeSingle();if(error||!data)throw new AppError("NOT_FOUND");return{...item,bucket:data.bucket,path:data.object_path};}

async function validateFile(file:File){if(!allowedMime.has(file.type)||file.size<=0||file.size>15*1024*1024)throw new AppError("VALIDATION_ERROR","Tệp không đúng định dạng hoặc vượt quá 15 MB.");return new Uint8Array(await file.arrayBuffer());}
function safeName(name:string){return name.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-120)||"document";}
export async function uploadCompanyDocument(user:AuthenticatedUser,file:File,input:{title:string;documentTypeId:string;expiryDate?:string}){if(!can(user.permissions,"document.company_manage")&&!can(user.permissions,"document.upload"))throw new AppError("PERMISSION_DENIED");const client=db(),actor=await resolvePlatformIdentity(client,user),bytes=await validateFile(file),fileId=crypto.randomUUID(),documentId=crypto.randomUUID(),path=`${new Date().getUTCFullYear()}/${documentId}/${fileId}-${safeName(file.name)}`;const{error:uploadError}=await client.storage.from("company-documents").upload(path,bytes,{contentType:file.type,upsert:false});if(uploadError)throw new AppError("SERVER_ERROR","Không thể tải tệp.");const{error:fileError}=await client.from("file_assets").insert({id:fileId,bucket:"company-documents",object_path:path,owner_entity_type:"company_document",owner_entity_id:documentId,mime_type:file.type,byte_size:file.size,visibility:"internal",created_by:actor.accountId,metadata:{originalName:file.name}});if(fileError){await client.storage.from("company-documents").remove([path]);throw new AppError("SERVER_ERROR");}const{error}=await client.from("documents").insert({id:documentId,title:input.title,document_type_id:input.documentTypeId,current_file_id:fileId,owner_entity_type:"company_document",owner_entity_id:documentId,owner_reference:"Tài liệu nội bộ",visibility_scope:"company_wide",expiry_date:input.expiryDate||null,uploaded_by:actor.accountId});if(error){await client.from("file_assets").delete().eq("id",fileId);await client.storage.from("company-documents").remove([path]);throw new AppError("SERVER_ERROR","Không thể lưu tài liệu.");}await client.from("document_versions").insert({document_id:documentId,version_number:1,file_id:fileId,uploaded_by:actor.accountId});await client.from("document_links").insert({document_id:documentId,entity_type:"company",entity_id:"company",relation_type:"COMPANY_DOCUMENT"});await recordAuditLog({actorId:actor.accountId,action:"document.created",entityType:"document",entityId:documentId,after:{title:input.title,documentTypeId:input.documentTypeId,expiryDate:input.expiryDate}});return getDocument(user,documentId);}
export async function replaceDocument(user:AuthenticatedUser,id:string,file:File,changeNote:string){if(!can(user.permissions,"document.replace"))throw new AppError("PERMISSION_DENIED");const client=db(),actor=await resolvePlatformIdentity(client,user),current=await getDocument(user,id);if(current.status!=="active")throw new AppError("CONFLICT","Tài liệu không ở trạng thái hoạt động.");const bytes=await validateFile(file),fileId=crypto.randomUUID(),version=current.currentVersion+1,path=`${new Date().getUTCFullYear()}/${id}/${fileId}-${safeName(file.name)}`;const{error:uploadError}=await client.storage.from("company-documents").upload(path,bytes,{contentType:file.type,upsert:false});if(uploadError)throw new AppError("SERVER_ERROR");const{error:fileError}=await client.from("file_assets").insert({id:fileId,bucket:"company-documents",object_path:path,owner_entity_type:"company_document",owner_entity_id:id,mime_type:file.type,byte_size:file.size,visibility:"internal",created_by:actor.accountId,metadata:{originalName:file.name}});if(fileError)throw new AppError("SERVER_ERROR");const{error}=await client.from("document_versions").insert({document_id:id,version_number:version,file_id:fileId,uploaded_by:actor.accountId,change_note:changeNote});if(error)throw new AppError("SERVER_ERROR");await client.from("documents").update({current_file_id:fileId,current_version:version}).eq("id",id).eq("current_version",current.currentVersion);await recordAuditLog({actorId:actor.accountId,action:"document.replaced",entityType:"document",entityId:id,before:{fileId:current.fileId,version:current.currentVersion},after:{fileId,version},reason:changeNote});await publishNotificationEvent({eventKey:"document.replaced",aggregateType:"document",aggregateId:id,actorAccountId:actor.accountId,idempotencyKey:`document:${id}:version:${version}`,recipients:[],values:{document_title:current.title},deepLink:`/documents/${id}`},client);return getDocument(user,id);}
export async function archiveDocument(user:AuthenticatedUser,id:string){if(!can(user.permissions,"document.archive"))throw new AppError("PERMISSION_DENIED");const client=db(),actor=await resolvePlatformIdentity(client,user),current=await getDocument(user,id);const{data,error}=await client.from("documents").update({status:"archived"}).eq("id",id).eq("status","active").select("id").maybeSingle();if(error||!data)throw new AppError("CONFLICT");await recordAuditLog({actorId:actor.accountId,action:"document.archived",entityType:"document",entityId:id,before:{status:current.status},after:{status:"archived"}});return{archived:true};}
