import {
  Bell, BookOpenCheck, Boxes, BriefcaseBusiness, Building2, Cable, Calculator, CalendarCheck, CalendarClock,
  CalendarDays, CalendarOff, CalendarRange, ChartNoAxesCombined, ChartSpline, CheckSquare, ClipboardCheck,
  ClipboardPenLine, Clock3, FileClock, FileSignature, FolderArchive, Handshake, HardHat, HeartPulse, History, IdCard,
  Landmark, LayoutDashboard, Library, MessageCircle, Newspaper, Package, PackageCheck, PackageMinus, PackagePlus,
  ReceiptText, Repeat, Scale, ScanLine, Send, Settings, ShieldAlert, ShieldCheck, Ship, SlidersHorizontal,
  TableProperties, Timer, Truck, UserCog, UserRound, Users, UsersRound, WalletCards, Warehouse,
  type LucideIcon
} from "lucide-react";

import type { NavigationIcon } from "@/config/navigation";

export const navigationIconMap: Record<NavigationIcon, LucideIcon> = {
  LayoutDashboard,
  Building2,
  IdCard,
  Users,
  Clock3,
  CalendarDays,
  CalendarRange,
  CalendarClock,
  Timer,
  BriefcaseBusiness,
  ClipboardCheck,
  Send,
  ClipboardPenLine,
  Warehouse,
  Package,
  PackagePlus,
  PackageMinus,
  Repeat,
  Boxes,
  Ship,
  Truck,
  FileSignature,
  CheckSquare,
  History,
  Newspaper,
  HardHat,
  Landmark,
  SlidersHorizontal,
  HeartPulse,
  UserCog,
  ShieldCheck,
  Settings,
  Bell,
  UserRound,
  UsersRound,
  WalletCards,
  MessageCircle,
  CalendarOff,
  CalendarCheck,
  TableProperties,
  FileClock,
  Scale,
  ScanLine,
  BookOpenCheck,
  Handshake,
  FolderArchive,
  Calculator,
  ReceiptText,
  Library,
  ChartNoAxesCombined,
  ChartSpline,
  Cable,
  PackageCheck,
  ShieldAlert
};

/** Shared sizing keeps navigation and launcher icons on one visual rhythm. */
export const navigationIconSizes = {
  compact: 14,
  launcherArrow: 16,
  action: 17,
  control: 18,
  rail: 19,
  mobile: 20,
  module: 23
} as const;
