import "server-only";
import {getServerEnv} from "@/lib/env";import {getSupabaseServiceClient} from "@/lib/supabase/server";import {AppError} from "@/lib/api/errors";import {logger} from "@/lib/logger";
function businessDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:getServerEnv().APP_TIMEZONE,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
export async function runDailyMaintenance(){const client=getSupabaseServiceClient();if(!client)throw new AppError("SERVER_ERROR","Database chưa được cấu hình.");const jobKey="daily-maintenance",idempotencyKey=businessDate();
  const{data,error}=await client.from("operational_job_runs").insert({job_key:jobKey,idempotency_key:idempotencyKey,status:"running"}).select("id").single();if(error?.code==="23505")return{status:"skipped",reason:"already_run",idempotencyKey};if(error||!data)throw new AppError("SERVER_ERROR","Không thể claim maintenance job.");const id=String(data.id);
  try{const cutoff=new Date(Date.now()-30*86400000).toISOString(),attemptCutoff=new Date(Date.now()-86400000).toISOString();const[expiredSessions,oldAttempts,expiredIdempotency,failedWebhooks,failedImports]=await Promise.all([
    client.from("app_sessions").delete({count:"exact"}).lt("expires_at",cutoff),client.from("auth_login_attempts").delete({count:"exact"}).lt("updated_at",attemptCutoff),client.from("api_idempotency_records").delete({count:"exact"}).lt("expires_at",new Date().toISOString()),client.from("webhook_deliveries").select("id",{head:true,count:"exact"}).in("status",["failed","dead_letter"]),client.from("import_jobs").select("id",{head:true,count:"exact"}).eq("status","failed")]);
    const result={expiredSessionsRemoved:expiredSessions.count||0,oldLoginWindowsRemoved:oldAttempts.count||0,expiredIdempotencyRemoved:expiredIdempotency.count||0,failedWebhooks:failedWebhooks.count||0,failedImports:failedImports.count||0};await client.from("operational_job_runs").update({status:"completed",completed_at:new Date().toISOString(),result}).eq("id",id);logger.info("operations.daily_maintenance_completed",{entityId:String(id),metadata:result});return{status:"completed",idempotencyKey,...result};
  }catch(error){await client.from("operational_job_runs").update({status:"failed",completed_at:new Date().toISOString(),error_code:error instanceof Error?error.name:"UNKNOWN"}).eq("id",id);logger.error("operations.daily_maintenance_failed",{entityId:String(id)});throw error;}}
