export type PartnerType = "supplier" | "forwarder" | "carrier" | "customs_broker" | "customer" | "other";
export type ContractStatus = "draft" | "active" | "partially_shipped" | "completed" | "cancelled";
export type ShipmentStatus = "planned" | "booked" | "in_transit" | "arrived_port" | "customs_processing" | "customs_cleared" | "delivering_to_warehouse" | "partially_received" | "received" | "completed" | "cancelled";
export type CustomsStatus = "not_started" | "preparing_documents" | "declared" | "inspection" | "pending_duty" | "cleared" | "issue";

export interface Partner { id:string; partnerCode:string; name:string; tradingName?:string; partnerTypes:PartnerType[]; country?:string; address?:string; email?:string; phone?:string; contactPerson?:string; taxRegistration?:string; status:"active"|"inactive"; note?:string; rowVersion:number; }
export interface ContractLine { id:string; lineNumber:number; itemId:string; itemCode:string; itemName:string; description:string; orderedQuantity:number; uomId:string; uomCode:string; unitPrice?:number; currency?:string; expectedDeliveryDate?:string; note?:string; shippedQuantity?:number; receivedQuantity?:number; remainingQuantity?:number; }
export interface ImportContract { id:string; contractNumber:string; supplierId:string; supplierName:string; orderDate:string; currency:string; incoterm?:string; paymentTerm?:string; expectedDeliveryDate?:string; status:ContractStatus; note?:string; rowVersion:number; lines:ContractLine[]; }
export interface ShipmentLine { id:string; lineNumber:number; contractLineId?:string; itemId:string; itemCode:string; itemName:string; specification?:string; expectedQuantity:number; uomId:string; uomCode:string; packageCount?:number; grossWeight?:number; netWeight?:number; volume?:number; marksNumbers?:string; note?:string; rowVersion:number; }
export interface ShipmentContainer { id:string; containerNumber:string; sealNumber?:string; containerType?:string; size?:string; grossWeight?:number; tareWeight?:number; status:string; note?:string; rowVersion:number; }
export interface ShipmentDocument { id:string; shipmentId:string; shipmentNumber?:string; documentTypeId:string; typeCode:string; typeName:string; documentNumber?:string; issueDate?:string; expiryDate?:string; issuer?:string; fileId:string; fileName:string; mimeType:string; sizeBytes:number; status:string; version:number; supersedesDocumentId?:string; note?:string; uploadedByName?:string; uploadedAt:string; }
export interface ScheduleEvent { id:string; scheduleType:"etd"|"eta"; oldValue?:string; newValue:string; reason?:string; source:string; changedByName?:string; changedAt:string; }
export interface ShipmentCustoms { status:CustomsStatus; declarationNumber?:string; declarationDate?:string; customsBrokerId?:string; customsBrokerName?:string; clearanceDate?:string; channel?:string; issueNote?:string; severity?:string; importDuty?:number; vat?:number; otherCharges?:number; currency?:string; note?:string; rowVersion:number; }
export interface Shipment { id:string; shipmentNumber:string; contractId?:string; contractNumber?:string; supplierId:string; supplierName:string; carrierId?:string; carrierName?:string; forwarderId?:string; forwarderName?:string; assignedAccountId?:string; transportMode:string; shipmentType:string; origin?:string; destination?:string; portOfLoading?:string; portOfDischarge?:string; bookingNumber?:string; billOfLadingNumber?:string; forwarderReference?:string; carrierReference?:string; plannedEtd?:string; currentEtd?:string; originalEta?:string; currentEta?:string; actualDeparture?:string; actualArrival?:string; status:ShipmentStatus; incoterm?:string; currency?:string; note?:string; updatedAt?:string; rowVersion:number; lines:ShipmentLine[]; containers:ShipmentContainer[]; documents:ShipmentDocument[]; customs:ShipmentCustoms; scheduleHistory:ScheduleEvent[]; receiving?:ReceivingSummary; attention?:AttentionFlag[]; }
export interface ReceivingLine { shipmentLineId:string; itemId:string; itemCode:string; itemName:string; uomId:string; uomCode:string; expectedQuantity:number; receivedQuantity:number; remainingQuantity:number; variance:number; shortResolved:boolean; }
export interface ReceivingSummary { expectedQuantity:number; receivedQuantity:number; remainingQuantity:number; progress:number; status:"not_received"|"partially_received"|"received"|"over_received"|"short_closed"; lines:ReceivingLine[]; receipts:Array<{id:string;documentNumber:string;documentDate:string;status:string;warehouseName?:string}>; }
export interface DocumentChecklistItem { documentTypeId:string; code:string; name:string; required:boolean; requiredBeforeCustoms:boolean; state:"missing"|"received"|"valid"|"expired"; documentId?:string; }
export interface AttentionFlag { code:"eta_delayed"|"document_missing"|"customs_issue"|"customs_delayed"|"arrival_not_received"|"short_unresolved"|"stale"; label:string; }
export interface ImportExportDashboard { inTransit:number; upcoming:number; customsProcessing:number; awaitingReceipt:number; attentionCount:number; upcomingArrivals:Shipment[]; needsAttention:Array<{shipment:Shipment;flags:AttentionFlag[]}>; }
export interface ImportExportSettings { shipmentPrefix:string; contractPrefix:string; overReceiptTolerancePercent:number; etaDelayDays:number; customsAttentionDays:number; arrivalNotReceivedDays:number; staleShipmentDays:number; }
export interface ShipmentTrackingUpdate { eta?:string; etd?:string; actualDeparture?:string; actualArrival?:string; event?:string; sourceReference?:string; }
export interface ShipmentTrackingProvider { readonly key:string; pull(shipment:Shipment):Promise<ShipmentTrackingUpdate[]>; }
