"use client";

import { Plus } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/shared/Button";
import { Card, StatCard } from "@/components/shared/Card";
import { DataTable, type DataTableColumn } from "@/components/shared/DataTable";
import { FilterBar } from "@/components/shared/FilterBar";
import { SearchInput, Select } from "@/components/shared/FormControls";
import { StatusBadge, type StatusBadgeTone } from "@/components/shared/StatusBadge";
import type { InventoryBalance, InventoryDocument, InventoryDocumentType, InventoryItem, StockCount, StockLedgerEntry, Warehouse, WarehouseDashboard } from "@/features/warehouse/types/warehouseTypes";
import { useDomainReconciliation } from "@/lib/realtime/useDomainReconciliation";

type ApiBody<T>={ok:boolean;data?:T;error?:{message?:string}};
async function api<T>(url:string):Promise<T>{const response=await fetch(url,{cache:"no-store"}),body=await response.json() as ApiBody<T>;if(!response.ok||!body.data)throw new Error(body.error?.message||"Không thể tải dữ liệu.");return body.data;}
function useWarehouseData<T>(url:string){const[data,setData]=useState<T>(),[error,setError]=useState<string>();const load=useCallback(()=>api<T>(url).then((value)=>{setData(value);setError(undefined);return value;}).catch((reason)=>{setError(reason instanceof Error?reason.message:"Không thể tải dữ liệu.");}),[url]);useEffect(()=>{void load();},[load]);useDomainReconciliation("warehouse",load);return{data,error,loading:!data&&!error};}
const number=new Intl.NumberFormat("vi-VN",{maximumFractionDigits:4});
const statusLabels:Record<string,string>={draft:"Nháp",submitted:"Đã gửi",posted:"Đã ghi sổ",cancelled:"Đã hủy",reversed:"Đã đảo",counting:"Đang kiểm",reviewed:"Đã đối chiếu",active:"Hoạt động",inactive:"Ngừng dùng",in_stock:"Còn hàng",low_stock:"Sắp hết",out_of_stock:"Hết hàng"};
function badge(value:string){const tone:StatusBadgeTone=value==="posted"||value==="active"||value==="in_stock"?"success":value==="low_stock"||value==="submitted"||value==="reviewed"?"warning":value==="out_of_stock"||value==="cancelled"?"error":"neutral";return <StatusBadge tone={tone}>{statusLabels[value]??value}</StatusBadge>;}
const typeConfig:Record<Exclude<InventoryDocumentType,"reversal">,{label:string;path:string}>={receipt:{label:"Nhập kho",path:"receipts"},issue:{label:"Xuất kho",path:"issues"},transfer:{label:"Chuyển kho",path:"transfers"},adjustment:{label:"Điều chỉnh",path:"adjustments"}};

export function WarehouseDashboardView(){const{data,error,loading}=useWarehouseData<WarehouseDashboard>("/api/v1/warehouse/dashboard");if(loading)return <Card>Đang tải…</Card>;if(error||!data)return <Card>{error}</Card>;const columns:DataTableColumn<InventoryDocument>[]=[{id:"number",header:"Số chứng từ",cell:(row)=><Link className="text-link" href={`/warehouse/${typeConfig[row.type as Exclude<InventoryDocumentType,"reversal">]?.path??"receipts"}/${row.id}`}>{row.documentNumber}</Link>},{id:"date",header:"Ngày",accessor:"documentDate"},{id:"type",header:"Loại",cell:(row)=>typeConfig[row.type as Exclude<InventoryDocumentType,"reversal">]?.label??"Đảo chứng từ"},{id:"warehouse",header:"Kho",cell:(row)=>row.sourceWarehouseName??row.targetWarehouseName??"—"},{id:"status",header:"Trạng thái",cell:(row)=>badge(row.status)}];return <div className="page-stack"><div className="content-grid warehouse-kpis"><StatCard label="Hàng hóa" value={String(data.itemCount)}/><StatCard label="Kho" value={String(data.warehouseCount)}/><StatCard label="Chờ xử lý" value={String(data.pendingDocuments)}/><StatCard label="Sắp hết / hết" value={String(data.lowStock+data.outOfStock)}/></div><Card><h3 className="section-title">Chứng từ gần đây</h3><DataTable columns={columns} data={data.recentDocuments} emptyDescription="" emptyTitle="Chưa có chứng từ" getRowId={(row)=>row.id}/></Card><Card><h3 className="section-title">Cảnh báo tồn kho</h3><DataTable columns={[{id:"item",header:"Hàng hóa",cell:(row:InventoryBalance)=>`${row.itemCode} · ${row.itemName}`},{id:"warehouse",header:"Kho",accessor:"warehouseName"},{id:"onHand",header:"Tồn",cell:(row:InventoryBalance)=>`${number.format(row.onHand)} ${row.uomCode}`,align:"right"},{id:"status",header:"Trạng thái",cell:(row:InventoryBalance)=>badge(row.status)}]} data={data.lowStockItems} emptyDescription="" emptyTitle="Không có cảnh báo" getRowId={(row)=>`${row.warehouseId}-${row.itemId}`}/></Card></div>;}

export function ItemListView(){const[search,setSearch]=useState("");const{data=[],error,loading}=useWarehouseData<InventoryItem[]>("/api/v1/items");const filtered=useMemo(()=>data.filter((row)=>`${row.itemCode} ${row.name}`.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi"))),[data,search]);const columns:DataTableColumn<InventoryItem>[]=[{id:"code",header:"Mã hàng",cell:(row)=><Link className="text-link" href={`/warehouse/items/${row.id}`}>{row.itemCode}</Link>},{id:"name",header:"Tên hàng",accessor:"name"},{id:"category",header:"Nhóm",cell:(row)=>row.categoryName??"—",hiddenOnMobile:true},{id:"uom",header:"ĐVT",accessor:"uomCode"},{id:"stock",header:"Tổng tồn",cell:(row)=>number.format(row.totalOnHand),align:"right"},{id:"status",header:"Trạng thái",cell:(row)=>badge(row.status)}];return <div className="page-stack"><FilterBar actions={<Link href="/warehouse/items/new"><Button leftIcon={<Plus size={16}/>} variant="primary">Thêm hàng hóa</Button></Link>}><SearchInput onChange={(event)=>setSearch(event.target.value)} placeholder="Mã hoặc tên hàng" value={search}/></FilterBar><DataTable columns={columns} data={filtered} emptyDescription="" emptyTitle="Chưa có hàng hóa" error={error} getRowId={(row)=>row.id} loading={loading}/></div>;}

export function WarehouseListView(){const{data=[],error,loading}=useWarehouseData<Warehouse[]>("/api/v1/warehouses");const columns:DataTableColumn<Warehouse>[]=[{id:"code",header:"Mã kho",cell:(row)=><Link className="text-link" href={`/warehouse/warehouses/${row.id}`}>{row.code}</Link>},{id:"name",header:"Tên kho",accessor:"name"},{id:"type",header:"Loại",accessor:"type"},{id:"project",header:"Dự án / công trường",cell:(row)=>[row.projectName,row.worksiteName].filter(Boolean).join(" · ")||"—",hiddenOnMobile:true},{id:"manager",header:"Quản lý",cell:(row)=>row.managerName??"—",hiddenOnMobile:true},{id:"status",header:"Trạng thái",cell:(row)=>badge(row.status)}];return <DataTable columns={columns} data={data} emptyDescription="" emptyTitle="Chưa có kho" error={error} getRowId={(row)=>row.id} loading={loading}/>;}

export function DocumentListView({type}:{type:Exclude<InventoryDocumentType,"reversal">}){const config=typeConfig[type],[status,setStatus]=useState(""),[search,setSearch]=useState("");const url=`/api/v1/warehouse/${config.path}?limit=100`,{data=[],error,loading}=useWarehouseData<InventoryDocument[]>(url);const filtered=useMemo(()=>data.filter((row)=>(!status||row.status===status)&&(!search||row.documentNumber.toLowerCase().includes(search.toLowerCase()))),[data,search,status]);const columns:DataTableColumn<InventoryDocument>[]=[{id:"number",header:"Số chứng từ",cell:(row)=><Link className="text-link" href={`/warehouse/${config.path}/${row.id}`}>{row.documentNumber}</Link>},{id:"date",header:"Ngày",accessor:"documentDate"},{id:"source",header:"Kho nguồn",cell:(row)=>row.sourceWarehouseName??"—",hiddenOnMobile:true},{id:"target",header:"Kho đích",cell:(row)=>row.targetWarehouseName??"—",hiddenOnMobile:true},{id:"transaction",header:"Loại giao dịch",accessor:"transactionTypeCode",hiddenOnMobile:true},{id:"status",header:"Trạng thái",cell:(row)=>badge(row.status)}];return <div className="page-stack"><FilterBar actions={<Link href={`/warehouse/${config.path}/new`}><Button leftIcon={<Plus size={16}/>} variant="primary">Tạo {config.label.toLowerCase()}</Button></Link>}><SearchInput onChange={(event)=>setSearch(event.target.value)} placeholder="Số chứng từ" value={search}/><Select label="Trạng thái" onChange={(event)=>setStatus(event.target.value)} options={Object.entries(statusLabels).filter(([key])=>["draft","submitted","posted","cancelled","reversed"].includes(key)).map(([value,label])=>({value,label}))} placeholder="Tất cả" value={status}/></FilterBar><DataTable columns={columns} data={filtered} emptyDescription="" emptyTitle="Chưa có chứng từ" error={error} getRowId={(row)=>row.id} loading={loading}/></div>;}

export function InventoryView(){const[warehouseId,setWarehouseId]=useState(""),[search,setSearch]=useState("");const warehouses=useWarehouseData<Warehouse[]>("/api/v1/warehouses"),inventory=useWarehouseData<InventoryBalance[]>(`/api/v1/warehouse/inventory${warehouseId?`?warehouseId=${warehouseId}`:""}`);const filtered=(inventory.data??[]).filter((row)=>`${row.itemCode} ${row.itemName}`.toLowerCase().includes(search.toLowerCase()));const columns:DataTableColumn<InventoryBalance>[]=[{id:"warehouse",header:"Kho",cell:(row)=>`${row.warehouseCode} · ${row.warehouseName}`},{id:"item",header:"Hàng hóa",cell:(row)=><Link className="text-link" href={`/warehouse/items/${row.itemId}`}>{row.itemCode} · {row.itemName}</Link>},{id:"category",header:"Nhóm",cell:(row)=>row.categoryName??"—",hiddenOnMobile:true},{id:"stock",header:"Tồn",cell:(row)=>`${number.format(row.onHand)} ${row.uomCode}`,align:"right"},{id:"minimum",header:"Tồn tối thiểu",cell:(row)=>row.minimumStock===undefined?"—":number.format(row.minimumStock),align:"right",hiddenOnMobile:true},{id:"status",header:"Trạng thái",cell:(row)=>badge(row.status)}];return <div className="page-stack"><FilterBar><SearchInput onChange={(event)=>setSearch(event.target.value)} placeholder="Mã hoặc tên hàng" value={search}/><Select label="Kho" onChange={(event)=>setWarehouseId(event.target.value)} options={(warehouses.data??[]).map((row)=>({value:row.id,label:`${row.code} · ${row.name}`}))} placeholder="Tất cả" value={warehouseId}/></FilterBar><DataTable columns={columns} data={filtered} emptyDescription="" emptyTitle="Chưa có số dư tồn kho" error={inventory.error||warehouses.error} getRowId={(row)=>`${row.warehouseId}-${row.itemId}`} loading={inventory.loading}/></div>;}

export function LedgerView(){const[warehouseId,setWarehouseId]=useState("");const warehouses=useWarehouseData<Warehouse[]>("/api/v1/warehouses"),ledger=useWarehouseData<StockLedgerEntry[]>(`/api/v1/warehouse/ledger?limit=200${warehouseId?`&warehouseId=${warehouseId}`:""}`);const columns:DataTableColumn<StockLedgerEntry>[]=[{id:"date",header:"Ngày",accessor:"postingDate"},{id:"document",header:"Chứng từ",cell:(row)=>row.documentNumber},{id:"warehouse",header:"Kho",accessor:"warehouseName"},{id:"item",header:"Hàng hóa",cell:(row)=>`${row.itemCode} · ${row.itemName}`},{id:"in",header:"Nhập",cell:(row)=>row.quantityIn?number.format(row.quantityIn):"—",align:"right"},{id:"out",header:"Xuất",cell:(row)=>row.quantityOut?number.format(row.quantityOut):"—",align:"right"},{id:"balance",header:"Tồn sau",cell:(row)=>`${number.format(row.runningBalance)} ${row.uomCode}`,align:"right"}];return <div className="page-stack"><FilterBar><Select label="Kho" onChange={(event)=>setWarehouseId(event.target.value)} options={(warehouses.data??[]).map((row)=>({value:row.id,label:`${row.code} · ${row.name}`}))} placeholder="Tất cả" value={warehouseId}/></FilterBar><DataTable columns={columns} data={ledger.data??[]} emptyDescription="" emptyTitle="Chưa có bút toán kho" error={ledger.error||warehouses.error} getRowId={(row)=>row.id} loading={ledger.loading}/></div>;}

export function StockCountListView(){const{data=[],error,loading}=useWarehouseData<StockCount[]>("/api/v1/warehouse/stock-counts");const columns:DataTableColumn<StockCount>[]=[{id:"number",header:"Số kiểm kê",cell:(row)=><Link className="text-link" href={`/warehouse/stock-counts/${row.id}`}>{row.countNumber}</Link>},{id:"date",header:"Ngày",accessor:"countDate"},{id:"warehouse",header:"Kho",accessor:"warehouseName"},{id:"policy",header:"Chính sách",cell:(row)=>row.transactionPolicy==="freeze"?"Khóa giao dịch":"Đối chiếu phát sinh"},{id:"status",header:"Trạng thái",cell:(row)=>badge(row.status)}];return <div className="page-stack"><FilterBar actions={<Link href="/warehouse/stock-counts/new"><Button leftIcon={<Plus size={16}/>} variant="primary">Tạo kiểm kê</Button></Link>}/><DataTable columns={columns} data={data} emptyDescription="" emptyTitle="Chưa có phiên kiểm kê" error={error} getRowId={(row)=>row.id} loading={loading}/></div>;}
