"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import type React from "react";

import { Button } from "@/components/shared/Button";
import { Card, StatCard } from "@/components/shared/Card";
import { Input, Select } from "@/components/shared/FormControls";
import { StatusBadge } from "@/components/shared/StatusBadge";
import type { EmployeePickerOption } from "@/features/employees/types";
import type { ProjectProgressNode } from "@/features/projects/types/projectTypes";

const typeLabels = { phase: "Giai đoạn", work_item: "Hạng mục", task: "Công việc", milestone: "Mốc", acceptance: "Nghiệm thu" };
const statusLabels = { not_started: "Chưa bắt đầu", in_progress: "Đang thực hiện", blocked: "Vướng mắc", completed: "Hoàn thành", cancelled: "Đã hủy" };

export function ProjectProgressTree({ projectId, employees, canEdit }: { projectId: string; employees: EmployeePickerOption[]; canEdit: boolean }) {
  const [nodes, setNodes] = useState<ProjectProgressNode[]>([]), [editing, setEditing] = useState<ProjectProgressNode>(), [parentId, setParentId] = useState<string>(), [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/v1/projects/${projectId}/progress`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message); setNodes(body.data); }, [projectId]);
  useEffect(() => { queueMicrotask(() => void load().catch((reason) => setError(reason.message))); }, [load]);
  const roots = useMemo(() => nodes.filter((node) => !node.parentId), [nodes]);
  const overall = roots.length ? Math.round(roots.reduce((sum, node) => sum + node.completionPercent, 0) / roots.length) : 0;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { id: editing?.id, rowVersion: editing?.rowVersion, parentId: editing?.parentId ?? parentId, nodeType: form.get("nodeType"), name: form.get("name"), status: form.get("status"), completionPercent: Number(form.get("completionPercent")), deadline: form.get("deadline") || undefined, assigneeEmployeeId: form.get("assigneeEmployeeId") || undefined, sortOrder: editing?.sortOrder ?? nodes.length }; const response = await fetch(`/api/v1/projects/${projectId}/progress`, { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) { setError(body.error?.message); return; } setNodes(body.data); setEditing(undefined); setParentId(undefined); setError(""); event.currentTarget.reset(); }
  function branch(node: ProjectProgressNode, depth = 0): React.ReactNode { const children = nodes.filter((item) => item.parentId === node.id); return <div key={node.id}><div className="project-progress-row" style={{ paddingInlineStart: `${depth * 24 + 12}px` }}><span><strong>{node.name}</strong><small>{typeLabels[node.nodeType]}{node.assigneeName ? ` · ${node.assigneeName}` : ""}</small></span><span className="project-progress-meter"><i style={{ width: `${node.completionPercent}%` }} />{node.completionPercent}%</span><span>{node.deadline ?? "—"}</span><StatusBadge tone={node.status === "completed" ? "success" : node.status === "blocked" ? "error" : node.status === "in_progress" ? "info" : "neutral"}>{statusLabels[node.status]}</StatusBadge>{canEdit ? <span className="form-actions"><Button onClick={() => { setEditing(node); setParentId(undefined); }} size="sm">Sửa</Button><Button onClick={() => { setEditing(undefined); setParentId(node.id); }} size="sm">Thêm cấp con</Button></span> : null}</div>{children.map((child) => branch(child, depth + 1))}</div>; }
  return <div className="page-stack"><div className="content-grid dashboard-kpi-grid"><StatCard label="Tiến độ tổng" value={`${overall}%`} /><StatCard label="Đang thực hiện" value={String(nodes.filter((node) => node.status === "in_progress").length)} /><StatCard label="Vướng mắc" value={String(nodes.filter((node) => node.status === "blocked").length)} /><StatCard label="Đã hoàn thành" value={String(nodes.filter((node) => node.status === "completed").length)} /></div><div className="content-grid content-grid--two"><Card><div className="panel-header"><h3>Cây tiến độ</h3>{canEdit ? <Button onClick={() => { setEditing(undefined); setParentId(undefined); }} variant="primary">Thêm giai đoạn</Button> : null}</div><div className="project-progress-tree">{roots.map((node) => branch(node))}</div>{!nodes.length ? <p>Chưa có hạng mục.</p> : null}</Card>{canEdit && (editing || parentId || !nodes.length) ? <Card><h3>{editing ? "Cập nhật hạng mục" : parentId ? "Thêm cấp con" : "Thêm giai đoạn"}</h3><form className="leave-form" key={editing?.id ?? parentId ?? "new"} onSubmit={submit}><div className="form-grid"><Input defaultValue={editing?.name} label="Tên hạng mục" name="name" required /><Select defaultValue={editing?.nodeType ?? (parentId ? "task" : "phase")} label="Loại" name="nodeType" options={Object.entries(typeLabels).map(([value, label]) => ({ value, label }))} /><Select defaultValue={editing?.status ?? "not_started"} label="Trạng thái" name="status" options={Object.entries(statusLabels).map(([value, label]) => ({ value, label }))} /><Input defaultValue={editing?.completionPercent ?? 0} label="Hoàn thành (%)" max="100" min="0" name="completionPercent" required type="number" /><Input defaultValue={editing?.deadline} label="Hạn hoàn thành" name="deadline" type="date" /><Select defaultValue={editing?.assigneeEmployeeId} label="Phụ trách" name="assigneeEmployeeId" options={employees.map((employee) => ({ value: employee.id, label: `${employee.code} · ${employee.name}` }))} placeholder="Chưa phân công" /></div><div className="form-actions"><Button onClick={() => { setEditing(undefined); setParentId(undefined); }} type="button">Hủy</Button><Button type="submit" variant="primary">Lưu</Button></div></form></Card> : null}</div>{error ? <p className="form-error">{error}</p> : null}</div>;
}
