import { z } from "zod";
const optionalText = (max: number) => z.preprocess((value) => value === "" || value == null ? undefined : value, z.string().trim().max(max).optional());
const optionalUuid = z.preprocess((value) => value === "" || value == null ? undefined : value, z.string().uuid().optional());

export const itemSchema = z.object({ itemCode: z.string().trim().min(2).max(50).regex(/^[A-Za-z0-9._/-]+$/), name: z.string().trim().min(2).max(240), shortName: optionalText(100), categoryId: optionalUuid, baseUomId: z.string().uuid(), specification: optionalText(500), brand: optionalText(120), manufacturer: optionalText(160), countryOfOrigin: optionalText(100), trackedInventory: z.boolean().default(true), status: z.enum(["active", "inactive"]).default("active"), note: optionalText(1000) });
export const itemPatchSchema = itemSchema.extend({ rowVersion: z.number().int().positive() });
export const categorySchema = z.object({ code: z.string().trim().min(2).max(40).regex(/^[A-Za-z0-9._/-]+$/), name: z.string().trim().min(2).max(160), parentId: optionalUuid, active: z.boolean().default(true), sortOrder: z.number().int().min(0).max(9999).default(0) });
export const uomSchema = z.object({ code: z.string().trim().min(1).max(20).regex(/^[A-Za-z0-9._/-]+$/), name: z.string().trim().min(1).max(80), symbol: z.string().trim().min(1).max(20), active: z.boolean().default(true) });
export const warehouseSchema = z.object({ code: z.string().trim().min(2).max(40).regex(/^[A-Za-z0-9._/-]+$/), name: z.string().trim().min(2).max(180), type: z.enum(["main", "worksite", "temporary", "bonded"]).default("main"), address: optionalText(300), managerEmployeeId: optionalUuid, projectId: optionalUuid, worksiteId: optionalUuid, status: z.enum(["active", "inactive"]).default("active"), note: optionalText(1000) }).superRefine((value, context) => { if (value.type === "worksite" && !value.projectId) context.addIssue({ code: z.ZodIssueCode.custom, path: ["projectId"], message: "Kho công trường cần chọn dự án." }); });
export const warehousePatchSchema = z.intersection(warehouseSchema, z.object({ rowVersion: z.number().int().positive() }));

export const documentLineSchema = z.object({ itemId: z.string().uuid(), quantity: z.number().positive().max(1_000_000_000), adjustmentQuantity: z.number().min(-1_000_000_000).max(1_000_000_000).optional(), uomId: z.string().uuid(), unitPrice: z.number().nonnegative().optional(), expectedQuantity: z.number().nonnegative().optional(), shipmentLineId: optionalUuid, reference: optionalText(160), purpose: optionalText(300), note: optionalText(500) });
const inventoryDocumentObject = z.object({ type: z.enum(["receipt", "issue", "transfer", "adjustment"]), clientRequestId: optionalUuid, documentDate: z.string().date(), sourceWarehouseId: optionalUuid, targetWarehouseId: optionalUuid, transactionTypeCode: z.string().trim().min(2).max(50), supplierReference: optionalText(160), shipmentId: optionalUuid, shipmentReceiptReference: optionalText(160), projectId: optionalUuid, worksiteId: optionalUuid, deliveredBy: optionalText(160), receivedBy: optionalText(160), recipient: optionalText(160), receivingDepartment: optionalText(160), note: optionalText(2000), lines: z.array(documentLineSchema).min(1).max(200) });
function validateInventoryDocument(value: z.infer<typeof inventoryDocumentObject>, context: z.RefinementCtx) {
  if ((value.type === "issue" || value.type === "adjustment") && !value.sourceWarehouseId) context.addIssue({ code: z.ZodIssueCode.custom, path: ["sourceWarehouseId"], message: "Chọn kho xuất/điều chỉnh." });
  if (value.type === "receipt" && !value.targetWarehouseId) context.addIssue({ code: z.ZodIssueCode.custom, path: ["targetWarehouseId"], message: "Chọn kho nhận." });
  if (value.type === "transfer" && (!value.sourceWarehouseId || !value.targetWarehouseId || value.sourceWarehouseId === value.targetWarehouseId)) context.addIssue({ code: z.ZodIssueCode.custom, path: ["targetWarehouseId"], message: "Kho nguồn và kho đích phải khác nhau." });
  if (value.type === "adjustment" && value.lines.some((line) => !line.adjustmentQuantity)) context.addIssue({ code: z.ZodIssueCode.custom, path: ["lines"], message: "Số lượng điều chỉnh phải khác 0." });
  if (value.type === "adjustment" && !value.note) context.addIssue({ code: z.ZodIssueCode.custom, path: ["note"], message: "Cần nhập lý do điều chỉnh." });
  const duplicates = value.lines.map((line) => line.itemId).filter((id, index, values) => values.indexOf(id) !== index); if (duplicates.length) context.addIssue({ code: z.ZodIssueCode.custom, path: ["lines"], message: "Một hàng hóa không được lặp trong cùng chứng từ." });
}
export const inventoryDocumentSchema = inventoryDocumentObject.superRefine(validateInventoryDocument);
export const inventoryDocumentPatchSchema = inventoryDocumentObject.omit({ type: true, clientRequestId: true }).extend({ rowVersion: z.number().int().positive() }).superRefine((value, context) => {
  const duplicates = value.lines.map((line) => line.itemId).filter((id, index, values) => values.indexOf(id) !== index);
  if (duplicates.length) context.addIssue({ code: z.ZodIssueCode.custom, path: ["lines"], message: "Một hàng hóa không được lặp trong cùng chứng từ." });
});
export const postDocumentSchema = z.object({ postingDate: z.string().date(), idempotencyKey: z.string().uuid(), allowNegativeOverride: z.boolean().default(false), overrideReason: optionalText(500) }).superRefine((value, context) => { if (value.allowNegativeOverride && !value.overrideReason) context.addIssue({ code: z.ZodIssueCode.custom, path: ["overrideReason"], message: "Cần nhập lý do cho phép âm kho." }); });
export const reverseDocumentSchema = z.object({ reason: z.string().trim().min(3).max(1000), idempotencyKey: z.string().uuid(), postingDate: z.string().date() });
export const stockCountSchema = z.object({ warehouseId: z.string().uuid(), countDate: z.string().date(), scope: z.enum(["all", "selected"]).default("all"), transactionPolicy: z.enum(["freeze", "reconcile"]).default("freeze"), itemIds: z.array(z.string().uuid()).max(1000).optional(), note: optionalText(1000) }).superRefine((value, context) => { if (value.scope === "selected" && !value.itemIds?.length) context.addIssue({ code: z.ZodIssueCode.custom, path: ["itemIds"], message: "Chọn ít nhất một hàng hóa." }); });
export const stockCountUpdateSchema = z.object({ rowVersion: z.number().int().positive(), lines: z.array(z.object({ id: z.string().uuid(), countedQuantity: z.number().nonnegative(), note: optionalText(500) })).min(1) });
export const warehouseListQuerySchema = z.object({ search: optionalText(200), warehouseId: optionalUuid, categoryId: optionalUuid, status: optionalText(40), type: optionalText(40), from: z.string().date().optional(), to: z.string().date().optional(), limit: z.coerce.number().int().min(1).max(200).default(50) });
