"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback,useEffect,useState } from "react";
import { Button } from "@/components/shared/Button";
import { Card } from "@/components/shared/Card";
import { Input,Select } from "@/components/shared/FormControls";
import { EmptyState } from "@/components/shared/States";
import { StatusBadge } from "@/components/shared/StatusBadge";

interface Workflow{id:string;code:string;name:string;domain_type:string;active:boolean;published_version:number;approval_workflow_versions:Array<{version:number;status:string;approval_workflow_steps:Array<{step_order:number;step_name:string;approver_source:string}>}>}
interface DraftStep{id:string;stepName:string;approverSource:string}
const sources=[{label:"Quản lý trực tiếp",value:"direct_manager"},{label:"Trưởng phòng",value:"department_manager"},{label:"Quản lý dự án",value:"project_manager"},{label:"HR",value:"hr_resolver"},{label:"Quản lý kho",value:"warehouse_manager"},{label:"Resolver nghiệp vụ",value:"domain_resolver"}];
const createStep=():DraftStep=>({id:crypto.randomUUID(),stepName:"",approverSource:"direct_manager"});

export function WorkflowManager(){
  const[items,setItems]=useState<Workflow[]>([]),[code,setCode]=useState(""),[name,setName]=useState(""),[domain,setDomain]=useState("LEAVE"),[steps,setSteps]=useState<DraftStep[]>([createStep()]),[message,setMessage]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/v1/approval-workflows"),body=await response.json() as{data?:Workflow[]};setItems(body.data??[]);},[]);
  useEffect(()=>{void load();},[load]);
  function patchStep(id:string,patch:Partial<DraftStep>){setSteps(current=>current.map(step=>step.id===id?{...step,...patch}:step));}
  async function publish(event:React.FormEvent){event.preventDefault();const response=await fetch("/api/v1/approval-workflows",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,name,domainType:domain,steps:steps.map(step=>({stepName:step.stepName,approverSource:step.approverSource,resolverConfig:{}}))})}),body=await response.json() as{error?:{message:string}};setMessage(response.ok?"Đã publish phiên bản mới.":body.error?.message??"Không thể publish.");if(response.ok){setCode("");setName("");setSteps([createStep()]);await load();}}
  return <div className="workflow-manager"><Card><h2>Quy trình đã publish</h2>{items.length?<div className="workflow-list">{items.map(item=>{const version=item.approval_workflow_versions.find(entry=>entry.version===item.published_version);return <article key={item.id}><div><strong>{item.name}</strong><span>{item.code} · {item.domain_type}</span></div><StatusBadge tone={item.active?"success":"neutral"}>v{item.published_version}</StatusBadge><ol>{version?.approval_workflow_steps.sort((a,b)=>a.step_order-b.step_order).map(step=><li key={step.step_order}>{step.step_order}. {step.step_name}</li>)}</ol></article>;})}</div>:<EmptyState title="Chưa có quy trình dùng chung"/>}</Card><Card><h2>Publish quy trình</h2><form onSubmit={event=>void publish(event)}><div className="form-grid"><Input required label="Mã" value={code} onChange={event=>setCode(event.target.value.toUpperCase())}/><Input required label="Tên" value={name} onChange={event=>setName(event.target.value)}/><Input required label="Nghiệp vụ" value={domain} onChange={event=>setDomain(event.target.value.toUpperCase())}/></div><div className="workflow-step-editor">{steps.map((step,index)=><fieldset key={step.id}><legend>Bước {index+1}</legend><Input required label="Tên bước" value={step.stepName} onChange={event=>patchStep(step.id,{stepName:event.target.value})}/><Select required label="Nguồn người duyệt" options={sources} value={step.approverSource} onChange={event=>patchStep(step.id,{approverSource:event.target.value})}/>{steps.length>1?<Button size="sm" onClick={()=>setSteps(current=>current.filter(item=>item.id!==step.id))}>Xóa bước</Button>:null}</fieldset>)}</div><Button onClick={()=>setSteps(current=>[...current,createStep()])}>Thêm bước</Button><div className="workflow-preview"><span>Người gửi</span>{steps.map((step,index)=><span className="workflow-preview__step" key={step.id}><b>↓</b><span>{step.stepName||`Bước ${index+1}`}</span></span>)}</div>{message?<p role="status">{message}</p>:null}<Button type="submit" variant="primary">Kiểm tra và publish</Button></form></Card></div>}
