import{createHash,createHmac,timingSafeEqual}from"node:crypto";import{isIP}from"node:net";
const blockedNames=new Set(["localhost","localhost.localdomain","metadata.google.internal"]);
function ipv4Number(value:string){const parts=value.split(".").map(Number);if(parts.length!==4||parts.some(part=>!Number.isInteger(part)||part<0||part>255))return;return parts.reduce((total,part)=>total*256+part,0)>>>0;}
export function isPublicIp(value:string){const ip=value.replace(/^::ffff:/,"");if(isIP(ip)===4){const n=ipv4Number(ip);if(n===undefined)return false;return !(n>>>24===10||n>>>24===127||n>>>24===0||n>>>16===0xa9fe||n>>>20===0xac1||n>>>16===0xc0a8||n>>>24>=224||n===0xffffffff||(n&0xffc00000)===0x64400000);}if(isIP(ip)===6){const lower=ip.toLowerCase();return !(lower==="::1"||lower==="::"||lower.startsWith("fc")||lower.startsWith("fd")||lower.startsWith("fe8")||lower.startsWith("fe9")||lower.startsWith("fea")||lower.startsWith("feb"));}return false;}
export function validateWebhookUrl(raw:string){let url:URL;try{url=new URL(raw);}catch{return{ok:false as const,error:"URL không hợp lệ."};}if(url.protocol!=="https:")return{ok:false as const,error:"Webhook bắt buộc dùng HTTPS."};if(url.username||url.password)return{ok:false as const,error:"URL không được chứa thông tin đăng nhập."};const host=url.hostname.toLowerCase().replace(/\.$/,"");if(blockedNames.has(host)||host.endsWith(".localhost")||host.endsWith(".local")||host.endsWith(".internal"))return{ok:false as const,error:"Hostname nội bộ không được phép."};if(isIP(host)&&!isPublicIp(host))return{ok:false as const,error:"Địa chỉ mạng riêng hoặc metadata không được phép."};return{ok:true as const,url};}
export async function assertPublicWebhookDestination(raw:string,lookup:(hostname:string)=>Promise<string[]>){const checked=validateWebhookUrl(raw);if(!checked.ok)throw new Error(checked.error);if(isIP(checked.url.hostname))return checked.url;const addresses=await lookup(checked.url.hostname);if(!addresses.length||addresses.some(address=>!isPublicIp(address)))throw new Error("DNS trỏ đến địa chỉ không được phép.");return checked.url;}
export function signWebhook(secret:string,timestamp:string,body:string){return`v1=${createHmac("sha256",secret).update(`${timestamp}.${body}`).digest("hex")}`;}
export function verifyWebhookSignature(secret:string,timestamp:string,body:string,signature:string,now=Date.now(),toleranceSeconds=300){const time=Number(timestamp);if(!Number.isFinite(time)||Math.abs(Math.floor(now/1000)-time)>toleranceSeconds)return false;const expected=Buffer.from(signWebhook(secret,timestamp,body)),received=Buffer.from(signature);return expected.length===received.length&&timingSafeEqual(expected,received);}
export function webhookRetry(attempt:number,status?:number,retryAfterSeconds?:number){if(status===429)return{retry:true,delaySeconds:Math.min(Math.max(retryAfterSeconds??60,1),43200),category:"rate_limit" as const};if(status===undefined||status>=500){const delays=[60,300,1800,7200,43200];return{retry:attempt<delays.length,delaySeconds:delays[Math.min(attempt-1,delays.length-1)],category:status===undefined?"network" as const:"transient" as const};}if(status===401||status===403)return{retry:false,delaySeconds:0,category:"auth" as const};if(status>=400)return{retry:false,delaySeconds:0,category:status===400||status===422?"validation" as const:"permanent" as const};return{retry:false,delaySeconds:0,category:"permanent" as const};}
const sensitive=/(authorization|api.?key|secret|token|password|cookie|cccd|national.?id|bank.?account)/i;
export function redactPayload(value:unknown):unknown{if(Array.isArray(value))return value.map(redactPayload);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,sensitive.test(key)?"[REDACTED]":redactPayload(item)]));return value;}
export function redactText(value:string){return value.replace(/(authorization|api[_-]?key|secret|token|password|cookie)\s*[:=]\s*[^\s,;]+/gi,"$1=[REDACTED]").slice(0,1000);}
export function safeRequestId(value:string|null){return value&&/^[A-Za-z0-9._:-]{8,64}$/.test(value)?value:crypto.randomUUID();}
export function bodyHash(body:string){return createHash("sha256").update(body).digest("hex");}
export function ipAllowed(ip:string|undefined,allowlist:readonly string[]){if(!allowlist.length)return true;if(!ip)return false;const normalized=ip.replace(/^::ffff:/,"");return allowlist.some(entry=>{if(!entry.includes("/"))return normalized===entry;const[address,bitsRaw]=entry.split("/"),bits=Number(bitsRaw);if(isIP(address)!==4||isIP(normalized)!==4||bits<0||bits>32)return false;const left=ipv4Number(address),right=ipv4Number(normalized);if(left===undefined||right===undefined)return false;const mask=bits===0?0:(0xffffffff<<(32-bits))>>>0;return(left&mask)===(right&mask);});}
export function validateEventData(schema:Record<string,unknown>,data:Record<string,unknown>){const required=Array.isArray(schema.required)?schema.required.filter(item=>typeof item==="string") as string[]:[];return required.filter(key=>!(key in data)).map(key=>`Thiếu trường ${key}.`);}
export function normalizeDeviceTimestamp(value:string,timeZone:string){if(/[zZ]$|[+-]\d{2}:?\d{2}$/.test(value)){const instant=new Date(value);if(Number.isNaN(instant.getTime()))throw new Error("INVALID_DEVICE_TIMESTAMP");return instant.toISOString();}const match=value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?$/);if(!match)throw new Error("INVALID_DEVICE_TIMESTAMP");const target=Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]),Number(match[4]),Number(match[5]),Number(match[6]),Number((match[7]??"").padEnd(3,"0"))),parts=(instant:number)=>Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date(instant)).map(part=>[part.type,part.value])),offset=(instant:number)=>{const zoned=parts(instant);return Date.UTC(Number(zoned.year),Number(zoned.month)-1,Number(zoned.day),Number(zoned.hour),Number(zoned.minute),Number(zoned.second))-instant;};let normalized=target-offset(target);normalized=target-offset(normalized);return new Date(normalized).toISOString();}
